// --- 1. CLINICAL DATABASES ---
// THE ULTIMATE MASTER PHARMACOPEIA
const drugsDb = [
    // --- ANTIBIOTICS ---
    { id: "ab_01", name: "Amoxicillin 125mg/5ml [Novamox / Synmox]", doseMg: 40, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 125, vol: 5, category: "antibiotics" },
    { id: "ab_02", name: "Amoxicillin 250mg/5ml [Novamox / Synmox]", doseMg: 40, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 250, vol: 5, category: "antibiotics" },
    { id: "ab_03", name: "Amox+Clav 62.5mg/ml drops [Augmentin]", doseMg: 40, doseType: "perDay", maxMg: 875, div: 3, defaultFreq: "TID", conc: 62.5, vol: 1, category: "antibiotics" },
    { id: "ab_04", name: "Amox+Clav 156mg/5ml [Augmentin / Clavam]", doseMg: 40, doseType: "perDay", maxMg: 875, div: 3, defaultFreq: "TID", conc: 156, vol: 5, category: "antibiotics" },
    { id: "ab_05", name: "Amox+Clav (200/28)mg/5ml [Advent]", doseMg: 40, doseType: "perDay", maxMg: 875, div: 2, defaultFreq: "BID", conc: 200, vol: 5, category: "antibiotics" },
    { id: "ab_06", name: "Amox+Clav 312mg/5ml [Augmentin Duo]", doseMg: 40, doseType: "perDay", maxMg: 875, div: 3, defaultFreq: "TID", conc: 312, vol: 5, category: "antibiotics" },
    { id: "ab_07", name: "Amox+Clav (400/57)mg/5ml [Clavam Forte]", doseMg: 40, doseType: "perDay", maxMg: 875, div: 2, defaultFreq: "BID", conc: 400, vol: 5, category: "antibiotics" },
    { id: "ab_08", name: "Amox+Clav (600/42.9)mg/5ml [Megamentin]", doseMg: 90, doseType: "perDay", maxMg: 875, div: 2, defaultFreq: "BID", conc: 600, vol: 5, category: "antibiotics" },
    { id: "ab_09", name: "Cefixime 100mg/5ml [Taxim-O / Zifi]", doseMg: 8, doseType: "perDay", maxMg: 200, div: 2, defaultFreq: "BID", conc: 100, vol: 5, category: "antibiotics" },
    { id: "ab_10", name: "Cefaclor 125mg/5ml [Keflor]", doseMg: 20, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 125, vol: 5, category: "antibiotics" },
    { id: "ab_11", name: "Cefaclor 250mg/5ml [Keflor]", doseMg: 20, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 250, vol: 5, category: "antibiotics" },
    { id: "ab_12", name: "Cefaclor 375mg/5ml [Keflor]", doseMg: 20, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 375, vol: 5, category: "antibiotics" },
    { id: "ab_13", name: "Cefuroxime 125mg/5ml [Ceftum / Zocef]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 125, vol: 5, category: "antibiotics" },
    { id: "ab_14", name: "Cefuroxime 250mg/5ml [Ceftum / Zocef]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 250, vol: 5, category: "antibiotics" },
    { id: "ab_15", name: "Cefdinir 125mg/5ml [Adcef]", doseMg: 14, doseType: "perDay", maxMg: 300, div: 1, defaultFreq: "QD or BID", conc: 125, vol: 5, category: "antibiotics" },
    { id: "ab_16", name: "Cefdinir 250mg/5ml [Adcef]", doseMg: 14, doseType: "perDay", maxMg: 300, div: 1, defaultFreq: "QD or BID", conc: 250, vol: 5, category: "antibiotics" },
    { id: "ab_17", name: "Cephalexin 125mg/5ml [Sporidex]", doseMg: 40, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 125, vol: 5, category: "antibiotics" },
    { id: "ab_18", name: "Cephalexin 250mg/5ml [Sporidex]", doseMg: 40, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 250, vol: 5, category: "antibiotics" },
    { id: "ab_19", name: "Cefadroxil 125mg/5ml [Odoxil]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 125, vol: 5, category: "antibiotics" },
    { id: "ab_20", name: "Cefadroxil 250mg/5ml [Odoxil]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 250, vol: 5, category: "antibiotics" },
    { id: "ab_21", name: "Cefadroxil 500mg/5ml [Odoxil]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 500, vol: 5, category: "antibiotics" },
    { id: "ab_22", name: "Cephradine 125mg/5ml", doseMg: 25, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 125, vol: 5, category: "antibiotics" },
    { id: "ab_23", name: "Cephradine 250mg/5ml", doseMg: 25, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 250, vol: 5, category: "antibiotics" },
    { id: "ab_24", name: "Cefpodoxime 40mg/5ml [Macpod / Cepodem]", doseMg: 10, doseType: "perDay", maxMg: 200, div: 2, defaultFreq: "BID", conc: 40, vol: 5, category: "antibiotics" },
    { id: "ab_25", name: "Cefpodoxime 50mg/5ml [Macpod / Cepodem]", doseMg: 10, doseType: "perDay", maxMg: 200, div: 2, defaultFreq: "BID", conc: 50, vol: 5, category: "antibiotics" },
    { id: "ab_26", name: "Cefpodoxime 100mg/5ml [Macpod / Cepodem]", doseMg: 10, doseType: "perDay", maxMg: 200, div: 2, defaultFreq: "BID", conc: 100, vol: 5, category: "antibiotics" },
    { id: "ab_27", name: "Cefprozil 125mg/5ml [Refzil O]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 125, vol: 5, category: "antibiotics" },
    { id: "ab_28", name: "Cefprozil 250mg/5ml [Refzil O]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 250, vol: 5, category: "antibiotics" },
    { id: "ab_29", name: "Azithromycin 100mg/5ml [Azee / Zithrox]", doseMg: 10, doseType: "perDose", maxMg: 500, div: 1, defaultFreq: "QD (3-5 days)", conc: 100, vol: 5, category: "antibiotics" },
    { id: "ab_30", name: "Azithromycin 200mg/5ml [Azee / Zithrox]", doseMg: 10, doseType: "perDose", maxMg: 500, div: 1, defaultFreq: "QD (3-5 days)", conc: 200, vol: 5, category: "antibiotics" },
    { id: "ab_31", name: "Erythromycin 200mg/5ml [Erythrocin]", doseMg: 40, doseType: "perDay", maxMg: 500, div: 4, defaultFreq: "QID", conc: 200, vol: 5, category: "antibiotics" },
    { id: "ab_32", name: "Erythromycin 400mg/5ml [Erythrocin]", doseMg: 40, doseType: "perDay", maxMg: 500, div: 4, defaultFreq: "QID", conc: 400, vol: 5, category: "antibiotics" },
    { id: "ab_33", name: "Clarithromycin 125mg/5ml [ClariBid]", doseMg: 15, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 125, vol: 5, category: "antibiotics" },
    { id: "ab_34", name: "Clarithromycin 250mg/5ml [ClariBid]", doseMg: 15, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 250, vol: 5, category: "antibiotics" },
    { id: "ab_35", name: "Mebendazole 100mg/5ml [Mebex]", doseMg: 100, doseType: "fixed", div: 1, defaultFreq: "Stat (Repeat 2wks)", conc: 100, vol: 5, category: "antibiotics" },
    { id: "ab_36", name: "Metronidazole 125mg/5ml [Flagyl]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 125, vol: 5, category: "antibiotics" },
    { id: "ab_37", name: "Metronidazole 200mg/5ml [Flagyl]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 200, vol: 5, category: "antibiotics" },
    { id: "ab_38", name: "Co-trimoxazole (40/200)mg/5ml [Septran]", doseMg: 8, doseType: "perDay", maxMg: 160, div: 2, defaultFreq: "BID", conc: 40, vol: 5, category: "antibiotics" },

    // --- ANTIPYRETICS & PAIN ---
    { id: "ap_01", name: "Paracetamol 100mg/ml drops [Calpol]", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 100, vol: 1, category: "antipyretics" },
    { id: "ap_02", name: "Paracetamol 120mg/5ml syrup [Calpol]", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 120, vol: 5, category: "antipyretics" },
    { id: "ap_03", name: "Paracetamol 125mg/5ml syrup [Calpol]", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 125, vol: 5, category: "antipyretics" },
    { id: "ap_04", name: "Paracetamol 250mg/5ml syrup [Calpol 250]", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 250, vol: 5, category: "antipyretics" },
    { id: "ap_05", name: "Paracetamol 500 mg Tablet [Crocin 500]", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, defaultFreq: "QID (PRN)", conc: 500, vol: 1, category: "antipyretics" },
    { id: "ap_06", name: "Paracetamol 650 mg Tablet [Dolo 650]", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, defaultFreq: "QID (PRN)", conc: 650, vol: 1, category: "antipyretics" },
    { id: "ap_07", name: "Paracetamol Suppository 80mg [Neomol]", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 80, vol: 1, category: "antipyretics" },
    { id: "ap_08", name: "Paracetamol Suppository 120mg [Neomol]", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 120, vol: 1, category: "antipyretics" },
    { id: "ap_09", name: "Paracetamol Suppository 250mg [Neomol]", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 250, vol: 1, category: "antipyretics" },
    { id: "ap_10", name: "Ibuprofen 40mg/ml drops [Ibugesic]", doseMg: 10, doseType: "perDose", maxMg: 400, div: 1, defaultFreq: "Q6-8H", conc: 40, vol: 1, category: "antipyretics" },
    { id: "ap_11", name: "Ibuprofen 100mg/5ml susp [Ibugesic / Brufen]", doseMg: 10, doseType: "perDose", maxMg: 400, div: 1, defaultFreq: "Q6-8H", conc: 100, vol: 5, category: "antipyretics" },
    { id: "ap_12", name: "Diclofenac Suppository 12.5mg [Voveran]", doseMg: 1, doseType: "fixed", maxMg: 50, div: 1, defaultFreq: "BID or TID", conc: 12.5, vol: 1, category: "antipyretics" },
    { id: "ap_13", name: "Diclofenac Suppository 25mg [Voveran]", doseMg: 1, doseType: "fixed", maxMg: 50, div: 1, defaultFreq: "BID or TID", conc: 25, vol: 1, category: "antipyretics" },

    // --- ANTIHISTAMINES & ALLERGY ---
    { id: "ah_01", name: "Dimetindene maleate 1mg/ml drops [Fenistil]", doseMg: 0.1, doseType: "perDay", maxMg: 1, div: 3, defaultFreq: "TID", conc: 1, vol: 1, category: "antihistamines" },
    { id: "ah_02", name: "Dimetindene maleate 0.1mg/ml syrup [Fenistil]", doseMg: 0.1, doseType: "perDay", maxMg: 1, div: 3, defaultFreq: "TID", conc: 0.1, vol: 1, category: "antihistamines" },
    { id: "ah_03", name: "Chlorpheniramine 2mg/5ml syrup [Piriton]", doseMg: 0.35, doseType: "perDay", maxMg: 4, div: 4, defaultFreq: "Q6H", conc: 2, vol: 5, category: "antihistamines" },
    { id: "ah_04", name: "Cetirizine 10mg/ml drops [Cetzine]", doseMg: 0.25, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "QD", conc: 10, vol: 1, category: "antihistamines" },
    { id: "ah_05", name: "Cetirizine 1mg/ml syrup [Cetzine]", doseMg: 0.25, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "QD", conc: 1, vol: 1, category: "antihistamines" },
    { id: "ah_06", name: "Cetirizine 5mg/5ml syrup [Cetzine]", doseMg: 0.25, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "QD", conc: 5, vol: 5, category: "antihistamines" },
    { id: "ah_07", name: "Levocetirizine 2.5mg/5ml syrup [Xyzal]", doseMg: 0.125, doseType: "perDose", maxMg: 5, div: 1, defaultFreq: "QD/HS", conc: 2.5, vol: 5, category: "antihistamines" },
    { id: "ah_08", name: "Loratadine 1mg/ml syrup [Claritin]", doseMg: 0.2, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "QD", conc: 1, vol: 1, category: "antihistamines" },
    { id: "ah_09", name: "Desloratadine 0.5mg/ml syrup [Aerius]", doseMg: 0.1, doseType: "perDose", maxMg: 5, div: 1, defaultFreq: "QD", conc: 0.5, vol: 1, category: "antihistamines" },
    { id: "ah_10", name: "Fexofenadine 30mg/5ml susp [Allegra]", doseMg: 2, doseType: "perDay", maxMg: 60, div: 2, defaultFreq: "BID", conc: 30, vol: 5, category: "antihistamines" },
    { id: "ah_11", name: "Promethazine 6.25mg/5ml syrup [Phenergan]", doseMg: 1, doseType: "perDay", maxMg: 25, div: 3, defaultFreq: "TID", conc: 6.25, vol: 5, category: "antihistamines" },
    { id: "ah_12", name: "Dexamethasone 0.5mg/5ml syrup [Dexona]", doseMg: 0.3, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "Stat or QD", conc: 0.5, vol: 5, category: "antihistamines" },
    { id: "ah_13", name: "Prednisolone 15mg/5ml syrup [Omnacortil]", doseMg: 1.5, doseType: "perDay", maxMg: 60, div: 2, defaultFreq: "BID", conc: 15, vol: 5, category: "antihistamines" },

    // --- GASTROINTESTINAL ---
    { id: "gi_01", name: "Domperidone 1mg/ml syrup [Domstal]", doseMg: 0.25, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "TID (Before meals)", conc: 1, vol: 1, category: "git" },
    { id: "gi_02", name: "Metoclopramide 5mg/5ml syrup [Perinorm]", doseMg: 0.15, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "TID", conc: 5, vol: 5, category: "git" },
    { id: "gi_03", name: "Ondansetron 4mg/5ml syrup [Emeset]", doseMg: 0.15, doseType: "perDose", maxMg: 8, div: 1, defaultFreq: "TID or Stat", conc: 4, vol: 5, category: "git" },
    { id: "gi_04", name: "Simethicone 40mg/ml drops [Colicaid]", doseMg: 1, doseType: "perDose", maxMg: 40, div: 1, defaultFreq: "QID (After meals)", conc: 40, vol: 1, category: "git" },
    { id: "gi_05", name: "Hyoscine butylbromide 5mg/5ml [Buscopan]", doseMg: 0.5, doseType: "perDose", maxMg: 20, div: 1, defaultFreq: "TID", conc: 5, vol: 5, category: "git" },
    { id: "gi_06", name: "Prifinium bromide 7.5mg/5ml", doseMg: 1, doseType: "perDose", maxMg: 30, div: 1, defaultFreq: "TID", conc: 7.5, vol: 5, category: "git" },
    { id: "gi_07", name: "Loperamide 1mg/5ml syrup [Imodium]", doseMg: 0.1, doseType: "perDose", maxMg: 2, div: 1, defaultFreq: "BID (Avoid <2 yrs)", conc: 1, vol: 5, category: "git" },
    { id: "gi_08", name: "Lactulose 66.7g/100ml syrup [Duphalac]", doseMg: 667, doseType: "perDay", maxMg: 2000, div: 2, defaultFreq: "BID", conc: 667, vol: 1, category: "git" },
    { id: "gi_09", name: "Glycerin Suppository [Hallens]", doseMg: 1, doseType: "fixed", div: 1, defaultFreq: "PRN", conc: 1, vol: 1, category: "git" },
    { id: "gi_10", name: "Syp Zinc (20mg/5ml)", doseMg: 20, doseType: "fixed", div: 1, defaultFreq: "OD", conc: 20, vol: 5, category: "git" },

    // --- RESPIRATORY ---
    { id: "rs_01", name: "Ascoril LS Junior Syrup", doseMg: 0, doseType: "fixed", div: 3, defaultFreq: "TID", conc: 0, vol: 5, category: "respiratory" },
    { id: "rs_02", name: "Kuff-X Syrup", doseMg: 0, doseType: "fixed", div: 3, defaultFreq: "TID", conc: 0, vol: 5, category: "respiratory" },
    { id: "rs_03", name: "Kuff-D Syrup", doseMg: 0, doseType: "fixed", div: 2, defaultFreq: "BID", conc: 0, vol: 5, category: "respiratory" },
    { id: "rs_04", name: "Ambroxol 7.5mg/ml drops [Ambrolite]", doseMg: 1.5, doseType: "perDay", maxMg: 30, div: 3, defaultFreq: "TID", conc: 7.5, vol: 1, category: "respiratory" },
    { id: "rs_05", name: "Ambroxol 15mg/5ml syrup [Ambrolite]", doseMg: 1.5, doseType: "perDay", maxMg: 30, div: 3, defaultFreq: "TID", conc: 15, vol: 5, category: "respiratory" },
    { id: "rs_06", name: "Ambroxol 30mg/5ml syrup [Ambrolite]", doseMg: 1.5, doseType: "perDay", maxMg: 30, div: 3, defaultFreq: "TID", conc: 30, vol: 5, category: "respiratory" },
    { id: "rs_07", name: "Bromhexine HCl 4mg/5ml syrup [Bisolvon]", doseMg: 1, doseType: "perDay", maxMg: 8, div: 3, defaultFreq: "TID", conc: 4, vol: 5, category: "respiratory" },
    { id: "rs_08", name: "Butamirate citrate 5mg/ml drops [Sinecod]", doseMg: 1, doseType: "perDay", maxMg: 15, div: 3, defaultFreq: "TID", conc: 5, vol: 1, category: "respiratory" },
    { id: "rs_09", name: "Butamirate citrate 7.5mg/5ml syrup [Sinecod]", doseMg: 1, doseType: "perDay", maxMg: 15, div: 3, defaultFreq: "TID", conc: 7.5, vol: 5, category: "respiratory" },
    { id: "rs_10", name: "Carbocisteine 2% (100mg/5ml) [Mucoclear]", doseMg: 20, doseType: "perDay", maxMg: 750, div: 3, defaultFreq: "TID", conc: 100, vol: 5, category: "respiratory" },
    { id: "rs_11", name: "Carbocisteine 5% (250mg/5ml) [Mucoclear]", doseMg: 20, doseType: "perDay", maxMg: 750, div: 3, defaultFreq: "TID", conc: 250, vol: 5, category: "respiratory" },
    { id: "rs_12", name: "Dextromethorphan 15mg/5ml syrup [Alex]", doseMg: 1, doseType: "perDay", maxMg: 30, div: 3, defaultFreq: "TID", conc: 15, vol: 5, category: "respiratory" },
    { id: "rs_13", name: "Guaifenesin 100mg/5ml syrup [Robitussin]", doseMg: 10, doseType: "perDay", maxMg: 400, div: 4, defaultFreq: "QID", conc: 100, vol: 5, category: "respiratory" },
    { id: "rs_14", name: "Terbutaline 1.5mg/5ml syrup [Bricanyl]", doseMg: 0.05, doseType: "perDose", maxMg: 2.5, div: 1, defaultFreq: "TID", conc: 1.5, vol: 5, category: "respiratory" },
    { id: "rs_15", name: "Salbutamol 2mg/5ml syrup [Asthalin]", doseMg: 0.15, doseType: "perDose", maxMg: 4, div: 1, defaultFreq: "TID", conc: 2, vol: 5, category: "respiratory" },
    { id: "rs_16", name: "Montelukast 4mg [Singulair]", doseMg: 0.2, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "QD (Evening)", conc: 4, vol: 1, category: "respiratory" },
    { id: "rs_17", name: "Chlorphen+Dextro (2/15) [Ascoril D]", doseMg: 1, doseType: "perDay", maxMg: 4, div: 3, defaultFreq: "TID", conc: 15, vol: 5, category: "respiratory" },
    { id: "rs_18", name: "Chlorphen+Pseudo (2/30) [Sinarest]", doseMg: 4, doseType: "perDay", maxMg: 60, div: 3, defaultFreq: "TID", conc: 30, vol: 5, category: "respiratory" },
    { id: "rs_19", name: "PCM+Chlorphen+Pseudo [Sinarest AF]", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, defaultFreq: "TID", conc: 125, vol: 5, category: "respiratory" },
    { id: "rs_20", name: "Triprolidine+Pseudo (1.25/30) [Actifed]", doseMg: 4, doseType: "perDay", maxMg: 60, div: 3, defaultFreq: "TID", conc: 30, vol: 5, category: "respiratory" },
    { id: "rs_21", name: "Guai+Tripro+Pseudo [Actifed Plus]", doseMg: 10, doseType: "perDay", maxMg: 400, div: 3, defaultFreq: "TID", conc: 100, vol: 5, category: "respiratory" }
];

    const foodsDb = [
        {name:"Boiled rice", cat:"Cereals", p:8.5, c:77, f:0, k:349},
        {name:"Raw rice", cat:"Cereals", p:7.5, c:76, f:0, k:346},
        {name:"Wheat", cat:"Cereals", p:12, c:71, f:0, k:346},
        {name:"Ragi", cat:"Cereals", p:7, c:72, f:0, k:328},
        {name:"Jowar", cat:"Cereals", p:10, c:72, f:0, k:349},
        {name:"Banana", cat:"Fruits", p:1.2, c:27, f:0, k:116},
        {name:"Apple", cat:"Fruits", p:0.2, c:13, f:0, k:59},
        {name:"Mango", cat:"Fruits", p:0.6, c:17, f:0, k:74},
        {name:"Dates(Dried)", cat:"Fruits", p:2.5, c:76, f:0, k:317},
        {name:"Sweet Lime", cat:"Fruits", p:1.5, c:11, f:0, k:60},
        {name:"Bengal gram", cat:"Pulses", p:17, c:61, f:0, k:360},
        {name:"Green gram", cat:"Pulses", p:24, c:60, f:0, k:348},
        {name:"Soya bean", cat:"Pulses", p:43, c:21, f:0, k:432},
        {name:"Rajmah", cat:"Pulses", p:23, c:60, f:0, k:346},
        {name:"Almond", cat:"Nuts", p:21, c:10, f:60, k:658},
        {name:"Groundnut", cat:"Nuts", p:25, c:26, f:40, k:567},
        {name:"Walnut", cat:"Nuts", p:34, c:11, f:64, k:687},
        {name:"Cow's milk", cat:"Dairy", p:3.3, c:4.4, f:4.1, k:67},
        {name:"Buffalo milk", cat:"Dairy", p:4.3, c:5.0, f:6.5, k:117},
        {name:"Breast milk", cat:"Dairy", p:1.1, c:7.4, f:3.4, k:65},
        {name:"Curds", cat:"Dairy", p:3.1, c:3.0, f:4.0, k:60},
        {name:"Chicken", cat:"Meat", p:25, c:0, f:0.6, k:109},
        {name:"Egg hen", cat:"Meat", p:13, c:0, f:13, k:173},
        {name:"Mutton", cat:"Meat", p:20, c:0, f:13, k:194},
        {name:"Potato", cat:"Vegetables", p:1, c:22, f:0.1, k:97},
        {name:"Carrot", cat:"Vegetables", p:1, c:11, f:0.2, k:48},
        {name:"Sweet potato", cat:"Vegetables", p:1, c:28, f:0.3, k:120},
        {name:"Beet root", cat:"Vegetables", p:1.7, c:9, f:0.1, k:43},
        {name:"Onion", cat:"Vegetables", p:1, c:11, f:0.1, k:50},
        {name:"Tapioca (chips)", cat:"Roots", p:1, c:82, f:0.3, k:338},
        {name:"Beef meat", cat:"Meat", p:19, c:0.2, f:10, k:410},
        {name:"Pork", cat:"Meat", p:18, c:0, f:4, k:114},
        {name:"Crab", cat:"Sea Food", p:9, c:3.3, f:1, k:59},
        {name:"Mackerel", cat:"Sea Food", p:19, c:0.5, f:1.7, k:93},
        {name:"Shrimp", cat:"Sea Food", p:68, c:0, f:8.5, k:349},
        {name:"Cauliflower", cat:"Vegetables", p:2.6, c:4, f:0.4, k:30},
        {name:"Capsicum", cat:"Vegetables", p:1.3, c:4.3, f:0.3, k:24},
        {name:"Coriander", cat:"Condiments", p:14, c:22, f:16, k:288},
        {name:"Garlic", cat:"Condiments", p:6, c:30, f:0.1, k:145},
        {name:"Ginger", cat:"Condiments", p:2, c:12, f:1, k:67}
    ];
    // Add this right below your foodsDb array
window.foodsDb = foodsDb;

    const baseVaccineSchema = [
        { id: "bcg", name: "BCG", window: "At Birth", group: "Infant", baseOffsetWeeks: 0, strategy: "Give ASAP." },
        { id: "opv0", name: "OPV-0", window: "At Birth", group: "Infant", baseOffsetWeeks: 0, strategy: "Max 15 days." },
        { id: "hepB0", name: "Hepatitis B-0", window: "At Birth", group: "Infant", baseOffsetWeeks: 0, strategy: "Give within 24h." },
        { id: "penta1", name: "Pentavalent-1", window: "6 Wks", group: "Infant", baseOffsetWeeks: 6, strategy: "Max 1 yr." },
        { id: "opv1", name: "OPV-1", window: "6 Wks", group: "Infant", baseOffsetWeeks: 6, strategy: "Up to 5 yrs." },
        { id: "fipv1", name: "fIPV-1", window: "6 Wks", group: "Infant", baseOffsetWeeks: 6, strategy: "Fractional dose (ID)." },
        { id: "pcv1", name: "PCV-1", window: "6 Wks", group: "Infant", baseOffsetWeeks: 6, strategy: "Max 1 yr." },
        { id: "penta2", name: "Pentavalent-2", window: "10 Wks", group: "Infant", baseOffsetWeeks: 10, dependsOn: "penta1", minIntervalWeeks: 4, strategy: "4wk gap." },
        { id: "opv2", name: "OPV-2", window: "10 Wks", group: "Infant", baseOffsetWeeks: 10, dependsOn: "opv1", minIntervalWeeks: 4, strategy: "4wk gap." },
        { id: "penta3", name: "Pentavalent-3", window: "14 Wks", group: "Infant", baseOffsetWeeks: 14, dependsOn: "penta2", minIntervalWeeks: 4, strategy: "4wk gap." },
        { id: "opv3", name: "OPV-3", window: "14 Wks", group: "Infant", baseOffsetWeeks: 14, dependsOn: "opv2", minIntervalWeeks: 4, strategy: "4wk gap." },
        { id: "fipv2", name: "fIPV-2", window: "14 Wks", group: "Infant", baseOffsetWeeks: 14, dependsOn: "fipv1", minIntervalWeeks: 8, strategy: "8wk gap." },
        { id: "pcv2", name: "PCV-2", window: "14 Wks", group: "Infant", baseOffsetWeeks: 14, dependsOn: "pcv1", minIntervalWeeks: 8, strategy: "8wk gap." },
        { id: "mr1", name: "MR-1", window: "9 Mos", group: "Infant", baseOffsetWeeks: 39, strategy: "Up to 5 yrs." },
        { id: "pcvB", name: "PCV Booster", window: "9 Mos", group: "Infant", baseOffsetWeeks: 39, dependsOn: "pcv2", minIntervalWeeks: 24, strategy: "6mo gap." },
        { id: "je1", name: "JE-1", window: "9 Mos", group: "Infant", baseOffsetWeeks: 39, condition: "je", strategy: "Endemic areas." },
        { id: "mr2", name: "MR-2", window: "16-24 Mos", group: "Toddler", baseOffsetWeeks: 69, dependsOn: "mr1", minIntervalWeeks: 24, strategy: "6mo gap." },
        { id: "dptB1", name: "DPT Booster-1", window: "16-24 Mos", group: "Toddler", baseOffsetWeeks: 69, dependsOn: "penta3", minIntervalWeeks: 24, strategy: "6mo gap required." },
        { id: "je2", name: "JE-2", window: "16-24 Mos", group: "Toddler", baseOffsetWeeks: 69, condition: "je", dependsOn: "je1", minIntervalWeeks: 24, strategy: "6mo gap." },
        { id: "dptB2", name: "DPT Booster-2", window: "5-6 Yrs", group: "Toddler", baseOffsetWeeks: 260, strategy: "Max 7 yrs." },
        { id: "hpv1", name: "HPV-1", window: "9-14 Yrs", group: "Adolescent", baseOffsetWeeks: 468, condition: "female", strategy: "Girls only." },
        { id: "hpv2", name: "HPV-2", window: "6 Mos Post Dose 1", group: "Adolescent", baseOffsetWeeks: 494, condition: "female", dependsOn: "hpv1", minIntervalWeeks: 24, strategy: "6mo gap." },
        { id: "td10", name: "Td-10", window: "10 Yrs", group: "Adolescent", baseOffsetWeeks: 520, strategy: "Tetanus/Diphtheria." },
        { id: "td16", name: "Td-16", window: "16 Yrs", group: "Adolescent", baseOffsetWeeks: 832, strategy: "Tetanus/Diphtheria." }
    ];

    const milestonesDb = {
        2: [ { id: "m2_1", domain: "Social", text: "Social smile.", sig: "Visual deficit." }, { id: "m2_2", domain: "Lang", text: "Coos.", sig: "Hearing deficit." }, { id: "m2_3", domain: "Motor", text: "Head steady.", sig: "Hypotonia." } ],
        4: [ { id: "m4_1", domain: "Social", text: "Laughs out loud.", sig: "Social delay." }, { id: "m4_2", domain: "Motor", text: "Reaches for toys.", sig: "Motor delay." }, { id: "m4_3", domain: "Motor", text: "Rolls tummy to back.", sig: "Hyper/hypotonia." } ],
        6: [ { id: "m6_1", domain: "Motor", text: "Sits without support.", sig: "CP red flag." }, { id: "m6_2", domain: "Lang", text: "Babbles.", sig: "Hearing loss." }, { id: "m6_3", domain: "Motor", text: "Transfers objects.", sig: "Hemiplegia." } ],
        9: [ { id: "m9_1", domain: "Motor", text: "Pincer grasp.", sig: "Fine motor delay." }, { id: "m9_2", domain: "Motor", text: "Pulls to stand.", sig: "Hypotonia." }, { id: "m9_3", domain: "Lang", text: "Responds to name.", sig: "Hearing/ASD." }, { id: "m9_4", domain: "Motor", text: "Pats a cake.", sig: "Coordination." } ],
        12: [ { id: "m12_1", domain: "Lang", text: "1-2 words.", sig: "Speech delay." }, { id: "m12_2", domain: "Motor", text: "Cruises/Walks.", sig: "Pathology." }, { id: "m12_3", domain: "Social", text: "Points to objects.", sig: "ASD risk." } ],
        18: [ { id: "m18_1", domain: "Motor", text: "Walks alone/backwards.", sig: "Neuro eval." }, { id: "m18_2", domain: "Lang", text: "10-15 words.", sig: "Speech delay." }, { id: "m18_3", domain: "Motor", text: "Uses spoon.", sig: "Coordination." } ],
        24: [ { id: "m24_1", domain: "Lang", text: "2-word sentences.", sig: "Speech eval." }, { id: "m24_2", domain: "Cognitive", text: "Points to 3 body parts.", sig: "Cognitive delay." }, { id: "m24_3", domain: "Social", text: "Parallel play.", sig: "ASD risk." } ],
        36: [ { id: "m36_1", domain: "Lang", text: "3-4 word sentences.", sig: "Articulation." }, { id: "m36_2", domain: "Motor", text: "Pedals tricycle.", sig: "Coordination." }, { id: "m36_3", domain: "Motor", text: "Copies a circle.", sig: "Visual-motor." } ]
    };

    // --- CLINICAL NUTRITION DATABASE ---
// Values are approximate per 100g or 100ml based on standard pediatric dietetics
const foodsDb = [
    { name: "Breastmilk / Formula (100ml)", calsPer100: 67, proPer100: 1.5 },
    { name: "Cow's Milk / Buffalo Milk (100ml)", calsPer100: 100, proPer100: 3.5 },
    { name: "Khichdi - Rice & Moong Dal (100g)", calsPer100: 120, proPer100: 4.0 },
    { name: "Plain Rice (100g cooked)", calsPer100: 130, proPer100: 2.7 },
    { name: "Thick Dal / Lentils (100g cooked)", calsPer100: 116, proPer100: 9.0 },
    { name: "Roti / Chapati (100g ~ 3 rotis)", calsPer100: 297, proPer100: 9.0 },
    { name: "Mashed Banana (100g)", calsPer100: 89, proPer100: 1.1 },
    { name: "Apple Puree (100g)", calsPer100: 52, proPer100: 0.3 },
    { name: "Boiled Egg (100g ~ 2 eggs)", calsPer100: 155, proPer100: 13.0 },
    { name: "Commercial Fortified Cereal (100g powder)", calsPer100: 412, proPer100: 15.0 },
    { name: "Curd / Yogurt (100g)", calsPer100: 98, proPer100: 11.0 },
    { name: "Idli (100g ~ 2 medium)", calsPer100: 144, proPer100: 4.0 },
    { name: "Dosa (100g ~ 1 large)", calsPer100: 280, proPer100: 5.0 },
    { name: "Upma / Suji (100g cooked)", calsPer100: 130, proPer100: 3.5 }
];

// Ensure it is globally available to the app
window.foodsDb = foodsDb;