// --- 1. CLINICAL DATABASES ---
// THE ULTIMATE MASTER PHARMACOPEIA
const drugsDb = [
    // --- ANTIBIOTICS ---
    { id: "ab_01", name: "Amoxicillin 125mg/5ml [Novamox / Synmox]", doseMg: 40, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 125, vol: 5, category: "antibiotics", indications: ['Ear Pain', 'Cough', 'Fever', 'Sore Throat'], warnings: ['⚠️ Check for Penicillin allergy.', '⚠️ Renal: GFR 10-30 give Q12H; GFR <10 give Q24H.'], orderSetTags: ['os_aom', 'os_uri'] },
    { id: "ab_02", name: "Amoxicillin 250mg/5ml [Novamox / Synmox]", doseMg: 40, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 250, vol: 5, category: "antibiotics", indications: ['Ear Pain', 'Cough', 'Fever', 'Sore Throat'], warnings: ['⚠️ Check for Penicillin allergy.', '⚠️ Renal: GFR 10-30 give Q12H; GFR <10 give Q24H.'], orderSetTags: ['os_aom', 'os_uri'] },
    { id: "ab_03", name: "Amox+Clav 62.5mg/ml drops [Augmentin]", doseMg: 40, doseType: "perDay", maxMg: 875, div: 3, defaultFreq: "TID", conc: 62.5, vol: 1, category: "antibiotics", indications: ['Ear Pain', 'Cough', 'Fever', 'Skin Rash'], warnings: ['⚠️ Check for Penicillin allergy.', '⚠️ Renal: GFR 10-30 give Q12H; GFR <10 give Q24H.'], orderSetTags: ['os_aom'] },
    { id: "ab_04", name: "Amox+Clav 156mg/5ml [Augmentin / Clavam]", doseMg: 40, doseType: "perDay", maxMg: 875, div: 3, defaultFreq: "TID", conc: 156, vol: 5, category: "antibiotics", indications: ['Ear Pain', 'Cough', 'Fever', 'Skin Rash'], warnings: ['⚠️ Check for Penicillin allergy.', 'May cause diarrhea.', '⚠️ Renal: GFR 10-30 give Q12H; GFR <10 give Q24H.'], orderSetTags: ['os_aom'] },
    { id: "ab_05", name: "Amox+Clav (200/28)mg/5ml [Advent]", doseMg: 40, doseType: "perDay", maxMg: 875, div: 2, defaultFreq: "BID", conc: 200, vol: 5, category: "antibiotics", indications: ['Ear Pain', 'Cough', 'Fever'], warnings: ['⚠️ Check for Penicillin allergy.', '⚠️ Renal: GFR <30 do not use BID formulations.'], orderSetTags: ['os_aom'] },
    { id: "ab_06", name: "Amox+Clav 312mg/5ml [Augmentin Duo]", doseMg: 40, doseType: "perDay", maxMg: 875, div: 3, defaultFreq: "TID", conc: 312, vol: 5, category: "antibiotics", indications: ['Ear Pain', 'Cough', 'Fever'], warnings: ['⚠️ Check for Penicillin allergy.', '⚠️ Renal: GFR 10-30 give Q12H; GFR <10 give Q24H.'], orderSetTags: ['os_aom'] },
    { id: "ab_07", name: "Amox+Clav (400/57)mg/5ml [Clavam Forte]", doseMg: 40, doseType: "perDay", maxMg: 875, div: 2, defaultFreq: "BID", conc: 400, vol: 5, category: "antibiotics", indications: ['Ear Pain', 'Cough', 'Fever'], warnings: ['⚠️ Check for Penicillin allergy.', '⚠️ Renal: GFR <30 do not use BID formulations.'], orderSetTags: ['os_aom'] },
    { id: "ab_08", name: "Amox+Clav (600/42.9)mg/5ml [Megamentin]", doseMg: 90, doseType: "perDay", maxMg: 875, div: 2, defaultFreq: "BID", conc: 600, vol: 5, category: "antibiotics", indications: ['Ear Pain', 'Cough', 'Fever'], warnings: ['⚠️ Check for Penicillin allergy.', '⚠️ Renal: GFR <30 do not use BID formulations.'], orderSetTags: ['os_aom'] },
    { id: "ab_09", name: "Cefixime 100mg/5ml [Taxim-O / Zifi]", doseMg: 8, doseType: "perDay", maxMg: 200, div: 2, defaultFreq: "BID", conc: 100, vol: 5, category: "antibiotics", indications: ['Fever', 'Loose Stools'], warnings: ['⚠️ Use with caution in cephalosporin allergy.', '⚠️ Renal: GFR 21-60 give 75% dose; GFR <20 give 50% dose.'], orderSetTags: ['os_age'] },
    { id: "ab_10", name: "Cefaclor 125mg/5ml [Keflor]", doseMg: 20, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 125, vol: 5, category: "antibiotics", indications: ['Fever', 'Sore Throat', 'Skin Rash'], warnings: ['⚠️ Renal: GFR <10 reduce dose by 50%.'], orderSetTags: [] },
    { id: "ab_11", name: "Cefaclor 250mg/5ml [Keflor]", doseMg: 20, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 250, vol: 5, category: "antibiotics", indications: ['Fever', 'Sore Throat', 'Skin Rash'], warnings: ['⚠️ Renal: GFR <10 reduce dose by 50%.'], orderSetTags: [] },
    { id: "ab_12", name: "Cefaclor 375mg/5ml [Keflor]", doseMg: 20, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 375, vol: 5, category: "antibiotics", indications: ['Fever', 'Sore Throat', 'Skin Rash'], warnings: ['⚠️ Renal: GFR <10 reduce dose by 50%.'], orderSetTags: [] },
    { id: "ab_13", name: "Cefuroxime 125mg/5ml [Ceftum / Zocef]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 125, vol: 5, category: "antibiotics", indications: ['Fever', 'Cough', 'Ear Pain'], warnings: ['⚠️ Renal: GFR 10-20 give Q24H; GFR <10 give Q48H.'], orderSetTags: [] },
    { id: "ab_14", name: "Cefuroxime 250mg/5ml [Ceftum / Zocef]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 250, vol: 5, category: "antibiotics", indications: ['Fever', 'Cough', 'Ear Pain'], warnings: ['⚠️ Renal: GFR 10-20 give Q24H; GFR <10 give Q48H.'], orderSetTags: [] },
    { id: "ab_15", name: "Cefdinir 125mg/5ml [Adcef]", doseMg: 14, doseType: "perDay", maxMg: 300, div: 1, defaultFreq: "QD or BID", conc: 125, vol: 5, category: "antibiotics", indications: ['Fever', 'Skin Rash'], warnings: ['⚠️ May cause red stools.', '⚠️ Renal: GFR <30 give 7 mg/kg/dose QD.'], orderSetTags: [] },
    { id: "ab_16", name: "Cefdinir 250mg/5ml [Adcef]", doseMg: 14, doseType: "perDay", maxMg: 300, div: 1, defaultFreq: "QD or BID", conc: 250, vol: 5, category: "antibiotics", indications: ['Fever', 'Skin Rash'], warnings: ['⚠️ May cause red stools.', '⚠️ Renal: GFR <30 give 7 mg/kg/dose QD.'], orderSetTags: [] },
    { id: "ab_17", name: "Cephalexin 125mg/5ml [Sporidex]", doseMg: 40, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 125, vol: 5, category: "antibiotics", indications: ['Skin Rash', 'Fever'], warnings: ['⚠️ Renal: GFR 10-50 give Q8-12H; GFR <10 give Q12-24H.'], orderSetTags: [] },
    { id: "ab_18", name: "Cephalexin 250mg/5ml [Sporidex]", doseMg: 40, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 250, vol: 5, category: "antibiotics", indications: ['Skin Rash', 'Fever'], warnings: ['⚠️ Renal: GFR 10-50 give Q8-12H; GFR <10 give Q12-24H.'], orderSetTags: [] },
    { id: "ab_19", name: "Cefadroxil 125mg/5ml [Odoxil]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 125, vol: 5, category: "antibiotics", indications: ['Skin Rash', 'Fever', 'Sore Throat'], warnings: ['⚠️ Renal: GFR 10-25 give Q24H; GFR <10 give Q36H.'], orderSetTags: [] },
    { id: "ab_20", name: "Cefadroxil 250mg/5ml [Odoxil]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 250, vol: 5, category: "antibiotics", indications: ['Skin Rash', 'Fever', 'Sore Throat'], warnings: ['⚠️ Renal: GFR 10-25 give Q24H; GFR <10 give Q36H.'], orderSetTags: [] },
    { id: "ab_21", name: "Cefadroxil 500mg/5ml [Odoxil]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 500, vol: 5, category: "antibiotics", indications: ['Skin Rash', 'Fever', 'Sore Throat'], warnings: ['⚠️ Renal: GFR 10-25 give Q24H; GFR <10 give Q36H.'], orderSetTags: [] },
    { id: "ab_22", name: "Cephradine 125mg/5ml", doseMg: 25, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 125, vol: 5, category: "antibiotics", indications: ['Skin Rash', 'Fever'], warnings: [], orderSetTags: [] },
    { id: "ab_23", name: "Cephradine 250mg/5ml", doseMg: 25, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 250, vol: 5, category: "antibiotics", indications: ['Skin Rash', 'Fever'], warnings: [], orderSetTags: [] },
    { id: "ab_24", name: "Cefpodoxime 40mg/5ml [Macpod / Cepodem]", doseMg: 10, doseType: "perDay", maxMg: 200, div: 2, defaultFreq: "BID", conc: 40, vol: 5, category: "antibiotics", indications: ['Fever', 'Cough', 'Ear Pain'], warnings: ['⚠️ Renal: GFR <30 increase interval to Q24H.'], orderSetTags: [] },
    { id: "ab_25", name: "Cefpodoxime 50mg/5ml [Macpod / Cepodem]", doseMg: 10, doseType: "perDay", maxMg: 200, div: 2, defaultFreq: "BID", conc: 50, vol: 5, category: "antibiotics", indications: ['Fever', 'Cough', 'Ear Pain'], warnings: ['⚠️ Renal: GFR <30 increase interval to Q24H.'], orderSetTags: [] },
    { id: "ab_26", name: "Cefpodoxime 100mg/5ml [Macpod / Cepodem]", doseMg: 10, doseType: "perDay", maxMg: 200, div: 2, defaultFreq: "BID", conc: 100, vol: 5, category: "antibiotics", indications: ['Fever', 'Cough', 'Ear Pain'], warnings: ['⚠️ Renal: GFR <30 increase interval to Q24H.'], orderSetTags: [] },
    { id: "ab_27", name: "Cefprozil 125mg/5ml [Refzil O]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 125, vol: 5, category: "antibiotics", indications: ['Fever', 'Cough', 'Ear Pain'], warnings: [], orderSetTags: [] },
    { id: "ab_28", name: "Cefprozil 250mg/5ml [Refzil O]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 250, vol: 5, category: "antibiotics", indications: ['Fever', 'Cough', 'Ear Pain'], warnings: [], orderSetTags: [] },
    { id: "ab_29", name: "Azithromycin 100mg/5ml [Azee / Zithrox]", doseMg: 10, doseType: "perDose", maxMg: 500, div: 1, defaultFreq: "QD (3-5 days)", conc: 100, vol: 5, category: "antibiotics", indications: ['Cough', 'Fever', 'Sore Throat'], warnings: ['⚠️ Monitor for QTc prolongation in high-risk patients.', '⚠️ Renal: Use caution if GFR <10.'], orderSetTags: ['os_uri'] },
    { id: "ab_30", name: "Azithromycin 200mg/5ml [Azee / Zithrox]", doseMg: 10, doseType: "perDose", maxMg: 500, div: 1, defaultFreq: "QD (3-5 days)", conc: 200, vol: 5, category: "antibiotics", indications: ['Cough', 'Fever', 'Sore Throat'], warnings: ['⚠️ Monitor for QTc prolongation in high-risk patients.', '⚠️ Renal: Use caution if GFR <10.'], orderSetTags: ['os_uri'] },
    { id: "ab_31", name: "Erythromycin 200mg/5ml [Erythrocin]", doseMg: 40, doseType: "perDay", maxMg: 500, div: 4, defaultFreq: "QID", conc: 200, vol: 5, category: "antibiotics", indications: ['Cough', 'Fever'], warnings: ['⚠️ High risk of GI upset.'], orderSetTags: [] },
    { id: "ab_32", name: "Erythromycin 400mg/5ml [Erythrocin]", doseMg: 40, doseType: "perDay", maxMg: 500, div: 4, defaultFreq: "QID", conc: 400, vol: 5, category: "antibiotics", indications: ['Cough', 'Fever'], warnings: ['⚠️ High risk of GI upset.'], orderSetTags: [] },
    { id: "ab_33", name: "Clarithromycin 125mg/5ml [ClariBid]", doseMg: 15, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 125, vol: 5, category: "antibiotics", indications: ['Cough', 'Fever'], warnings: ['⚠️ Strong CYP3A4 inhibitor.'], orderSetTags: [] },
    { id: "ab_34", name: "Clarithromycin 250mg/5ml [ClariBid]", doseMg: 15, doseType: "perDay", maxMg: 500, div: 2, defaultFreq: "BID", conc: 250, vol: 5, category: "antibiotics", indications: ['Cough', 'Fever'], warnings: ['⚠️ Strong CYP3A4 inhibitor.'], orderSetTags: [] },
    { id: "ab_35", name: "Mebendazole 100mg/5ml [Mebex]", doseMg: 100, doseType: "fixed", maxMg: 100, div: 1, defaultFreq: "Stat (Repeat 2wks)", conc: 100, vol: 5, category: "antibiotics", indications: ['Itching', 'Worms'], warnings: [], orderSetTags: [] },
    { id: "ab_36", name: "Metronidazole 125mg/5ml [Flagyl]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 125, vol: 5, category: "antibiotics", indications: ['Loose Stools', 'Abdominal Pain'], warnings: ['⚠️ Administer with food to minimize GI irritation.', '⚠️ Renal: GFR <10 give 50% dose Q12H.'], orderSetTags: ['os_age'] },
    { id: "ab_37", name: "Metronidazole 200mg/5ml [Flagyl]", doseMg: 30, doseType: "perDay", maxMg: 500, div: 3, defaultFreq: "TID", conc: 200, vol: 5, category: "antibiotics", indications: ['Loose Stools', 'Abdominal Pain'], warnings: ['⚠️ Administer with food to minimize GI irritation.', '⚠️ Renal: GFR <10 give 50% dose Q12H.'], orderSetTags: ['os_age'] },
    { id: "ab_38", name: "Co-trimoxazole (40/200)mg/5ml [Septran]", doseMg: 8, doseType: "perDay", maxMg: 160, div: 2, defaultFreq: "BID", conc: 40, vol: 5, category: "antibiotics", indications: ['Fever', 'Cough', 'Skin Rash'], warnings: ['⚠️ Contraindicated in sulfa allergy.', '⚠️ Renal: GFR 15-30 give 50% dose; GFR <15 AVOID.'], orderSetTags: [] },

    // --- ANTIPYRETICS & PAIN ---
    { id: "ap_01", name: "Paracetamol 100mg/ml drops [Calpol]", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 100, vol: 1, category: "antipyretics", indications: ['Fever', 'Pain'], warnings: ['⚠️ Risk of hepatotoxicity with overdose.', '⚠️ Renal: GFR 10-50 give Q6H; GFR <10 give Q8H.'], orderSetTags: ['os_fever'] },
    { id: "ap_02", name: "Paracetamol 120mg/5ml syrup [Calpol]", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 120, vol: 5, category: "antipyretics", indications: ['Fever', 'Pain'], warnings: ['⚠️ Risk of hepatotoxicity with overdose.', '⚠️ Renal: GFR 10-50 give Q6H; GFR <10 give Q8H.'], orderSetTags: ['os_fever'] },
    { id: "ap_03", name: "Paracetamol 125mg/5ml syrup [Calpol]", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 125, vol: 5, category: "antipyretics", indications: ['Fever', 'Pain'], warnings: ['⚠️ Risk of hepatotoxicity with overdose.', '⚠️ Renal: GFR 10-50 give Q6H; GFR <10 give Q8H.'], orderSetTags: ['os_fever'] },
    { id: "ap_04", name: "Paracetamol 250mg/5ml syrup [Calpol 250]", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 250, vol: 5, category: "antipyretics", indications: ['Fever', 'Pain'], warnings: ['⚠️ Risk of hepatotoxicity with overdose.', '⚠️ Renal: GFR 10-50 give Q6H; GFR <10 give Q8H.'], orderSetTags: ['os_fever'] },
    { id: "ap_05", name: "Paracetamol 500 mg Tablet [Crocin 500]", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, defaultFreq: "QID (PRN)", conc: 500, vol: 1, category: "antipyretics", indications: ['Fever', 'Pain'], warnings: ['⚠️ Risk of hepatotoxicity with overdose.'], orderSetTags: ['os_fever'] },
    { id: "ap_06", name: "Paracetamol 650 mg Tablet [Dolo 650]", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, defaultFreq: "QID (PRN)", conc: 650, vol: 1, category: "antipyretics", indications: ['Fever', 'Pain'], warnings: ['⚠️ Risk of hepatotoxicity with overdose.'], orderSetTags: ['os_fever'] },
    { id: "ap_07", name: "Paracetamol Suppository 80mg [Neomol]", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 80, vol: 1, category: "antipyretics", indications: ['Fever', 'Pain'], warnings: [], orderSetTags: ['os_fever'] },
    { id: "ap_08", name: "Paracetamol Suppository 120mg [Neomol]", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 120, vol: 1, category: "antipyretics", indications: ['Fever', 'Pain'], warnings: [], orderSetTags: ['os_fever'] },
    { id: "ap_09", name: "Paracetamol Suppository 250mg [Neomol]", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, defaultFreq: "Q6H PRN", conc: 250, vol: 1, category: "antipyretics", indications: ['Fever', 'Pain'], warnings: [], orderSetTags: ['os_fever'] },
    { id: "ap_10", name: "Ibuprofen 40mg/ml drops [Ibugesic]", doseMg: 10, doseType: "perDose", maxMg: 400, div: 1, defaultFreq: "Q6-8H", conc: 40, vol: 1, category: "antipyretics", indications: ['Fever', 'Pain'], warnings: ['⚠️ Administer with food to minimize GI upset.', '⚠️ Renal: AVOID in significant renal impairment.'], orderSetTags: [] },
    { id: "ap_11", name: "Ibuprofen 100mg/5ml susp [Ibugesic / Brufen]", doseMg: 10, doseType: "perDose", maxMg: 400, div: 1, defaultFreq: "Q6-8H", conc: 100, vol: 5, category: "antipyretics", indications: ['Fever', 'Pain'], warnings: ['⚠️ Administer with food to minimize GI upset.', '⚠️ Renal: AVOID in significant renal impairment.'], orderSetTags: [] },
    { id: "ap_12", name: "Diclofenac Suppository 12.5mg [Voveran]", doseMg: 1, doseType: "fixed", maxMg: 50, div: 1, defaultFreq: "BID or TID", conc: 12.5, vol: 1, category: "antipyretics", indications: ['Pain'], warnings: ['⚠️ Avoid in active GI bleeding.', '⚠️ Renal: AVOID in severe renal impairment.'], orderSetTags: [] },
    { id: "ap_13", name: "Diclofenac Suppository 25mg [Voveran]", doseMg: 1, doseType: "fixed", maxMg: 50, div: 1, defaultFreq: "BID or TID", conc: 25, vol: 1, category: "antipyretics", indications: ['Pain'], warnings: ['⚠️ Avoid in active GI bleeding.', '⚠️ Renal: AVOID in severe renal impairment.'], orderSetTags: [] },

    // --- ANTIHISTAMINES & ALLERGY ---
    { id: "ah_01", name: "Dimetindene maleate 1mg/ml drops [Fenistil]", doseMg: 0.1, doseType: "perDay", maxMg: 1, div: 3, defaultFreq: "TID", conc: 1, vol: 1, category: "antihistamines", indications: ['Cold', 'Itching', 'Sneezing'], warnings: ['⚠️ May cause significant sedation.'], orderSetTags: ['os_uri'] },
    { id: "ah_02", name: "Dimetindene maleate 0.1mg/ml syrup [Fenistil]", doseMg: 0.1, doseType: "perDay", maxMg: 1, div: 3, defaultFreq: "TID", conc: 0.1, vol: 1, category: "antihistamines", indications: ['Cold', 'Itching', 'Sneezing'], warnings: ['⚠️ May cause significant sedation.'], orderSetTags: ['os_uri'] },
    { id: "ah_03", name: "Chlorpheniramine 2mg/5ml syrup [Piriton]", doseMg: 0.35, doseType: "perDay", maxMg: 4, div: 4, defaultFreq: "Q6H", conc: 2, vol: 5, category: "antihistamines", indications: ['Cold', 'Itching', 'Sneezing'], warnings: ['⚠️ May cause significant sedation.'], orderSetTags: ['os_uri'] },
    { id: "ah_04", name: "Cetirizine 10mg/ml drops [Cetzine]", doseMg: 0.25, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "QD", conc: 10, vol: 1, category: "antihistamines", indications: ['Cold', 'Itching', 'Sneezing'], warnings: ['⚠️ Renal: GFR 11-31 decrease to QOD (every other day).'], orderSetTags: ['os_uri'] },
    { id: "ah_05", name: "Cetirizine 1mg/ml syrup [Cetzine]", doseMg: 0.25, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "QD", conc: 1, vol: 1, category: "antihistamines", indications: ['Cold', 'Itching', 'Sneezing'], warnings: ['⚠️ Renal: GFR 11-31 decrease to QOD.'], orderSetTags: ['os_uri'] },
    { id: "ah_06", name: "Cetirizine 5mg/5ml syrup [Cetzine]", doseMg: 0.25, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "QD", conc: 5, vol: 5, category: "antihistamines", indications: ['Cold', 'Itching', 'Sneezing'], warnings: ['⚠️ Renal: GFR 11-31 decrease to QOD.'], orderSetTags: ['os_uri'] },
    { id: "ah_07", name: "Levocetirizine 2.5mg/5ml syrup [Xyzal]", doseMg: 0.125, doseType: "perDose", maxMg: 5, div: 1, defaultFreq: "QD/HS", conc: 2.5, vol: 5, category: "antihistamines", indications: ['Cold', 'Itching', 'Sneezing'], warnings: ['⚠️ Renal: GFR 30-50 give QOD; GFR <30 give Q3Days.'], orderSetTags: ['os_uri'] },
    { id: "ah_08", name: "Loratadine 1mg/ml syrup [Claritin]", doseMg: 0.2, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "QD", conc: 1, vol: 1, category: "antihistamines", indications: ['Cold', 'Itching', 'Sneezing'], warnings: [], orderSetTags: ['os_uri'] },
    { id: "ah_09", name: "Desloratadine 0.5mg/ml syrup [Aerius]", doseMg: 0.1, doseType: "perDose", maxMg: 5, div: 1, defaultFreq: "QD", conc: 0.5, vol: 1, category: "antihistamines", indications: ['Cold', 'Itching', 'Sneezing'], warnings: [], orderSetTags: ['os_uri'] },
    { id: "ah_10", name: "Fexofenadine 30mg/5ml susp [Allegra]", doseMg: 2, doseType: "perDay", maxMg: 60, div: 2, defaultFreq: "BID", conc: 30, vol: 5, category: "antihistamines", indications: ['Cold', 'Itching', 'Sneezing'], warnings: [], orderSetTags: ['os_uri'] },
    { id: "ah_11", name: "Promethazine 6.25mg/5ml syrup [Phenergan]", doseMg: 1, doseType: "perDay", maxMg: 25, div: 3, defaultFreq: "TID", conc: 6.25, vol: 5, category: "antihistamines", indications: ['Nausea', 'Vomiting', 'Itching'], warnings: ['⚠️ Contraindicated in children < 2 years.'], orderSetTags: [] },
    { id: "ah_12", name: "Dexamethasone 0.5mg/5ml syrup [Dexona]", doseMg: 0.3, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "Stat or QD", conc: 0.5, vol: 5, category: "antihistamines", indications: ['Skin Rash', 'Wheezing'], warnings: ['⚠️ Short burst therapy usually does not require tapering.'], orderSetTags: [] },
    { id: "ah_13", name: "Prednisolone 15mg/5ml syrup [Omnacortil]", doseMg: 1.5, doseType: "perDay", maxMg: 60, div: 2, defaultFreq: "BID", conc: 15, vol: 5, category: "antihistamines", indications: ['Skin Rash', 'Wheezing'], warnings: ['⚠️ Give after meals to prevent gastric irritation.'], orderSetTags: ['os_asthma'] },

    // --- GASTROINTESTINAL ---
    { id: "gi_01", name: "Domperidone 1mg/ml syrup [Domstal]", doseMg: 0.25, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "TID (Before meals)", conc: 1, vol: 1, category: "git", indications: ['Vomiting', 'Nausea'], warnings: ['⚠️ Risk of extrapyramidal symptoms.'], orderSetTags: ['os_age'] },
    { id: "gi_02", name: "Metoclopramide 5mg/5ml syrup [Perinorm]", doseMg: 0.15, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "TID", conc: 5, vol: 5, category: "git", indications: ['Vomiting', 'Nausea'], warnings: ['⚠️ Risk of extrapyramidal symptoms (dystonia).'], orderSetTags: ['os_age'] },
    { id: "gi_03", name: "Ondansetron 4mg/5ml syrup [Emeset]", doseMg: 0.15, doseType: "perDose", maxMg: 8, div: 1, defaultFreq: "TID or Stat", conc: 4, vol: 5, category: "git", indications: ['Vomiting', 'Nausea'], warnings: ['⚠️ Monitor for QTc prolongation.'], orderSetTags: ['os_age'] },
    { id: "gi_04", name: "Simethicone 40mg/ml drops [Colicaid]", doseMg: 1, doseType: "perDose", maxMg: 40, div: 1, defaultFreq: "QID (After meals)", conc: 40, vol: 1, category: "git", indications: ['Abdominal Pain'], warnings: [], orderSetTags: [] },
    { id: "gi_05", name: "Hyoscine butylbromide 5mg/5ml [Buscopan]", doseMg: 0.5, doseType: "perDose", maxMg: 20, div: 1, defaultFreq: "TID", conc: 5, vol: 5, category: "git", indications: ['Abdominal Pain'], warnings: [], orderSetTags: [] },
    { id: "gi_06", name: "Prifinium bromide 7.5mg/5ml", doseMg: 1, doseType: "perDose", maxMg: 30, div: 1, defaultFreq: "TID", conc: 7.5, vol: 5, category: "git", indications: ['Abdominal Pain'], warnings: [], orderSetTags: [] },
    { id: "gi_07", name: "Loperamide 1mg/5ml syrup [Imodium]", doseMg: 0.1, doseType: "perDose", maxMg: 2, div: 1, defaultFreq: "BID (Avoid <2 yrs)", conc: 1, vol: 5, category: "git", indications: ['Loose Stools'], warnings: ['⚠️ Avoid in children < 2 years.'], orderSetTags: [] },
    { id: "gi_08", name: "Lactulose 66.7g/100ml syrup [Duphalac]", doseMg: 667, doseType: "perDay", maxMg: 2000, div: 2, defaultFreq: "BID", conc: 667, vol: 1, category: "git", indications: ['Abdominal Pain'], warnings: [], orderSetTags: [] },
    { id: "gi_09", name: "Glycerin Suppository [Hallens]", doseMg: 1, doseType: "fixed", maxMg: 1, div: 1, defaultFreq: "PRN", conc: 1, vol: 1, category: "git", indications: ['Abdominal Pain'], warnings: [], orderSetTags: [] },
    { id: "gi_10", name: "Syp Zinc (20mg/5ml)", doseMg: 20, doseType: "fixed", maxMg: 20, div: 1, defaultFreq: "OD", conc: 20, vol: 5, category: "git", indications: ['Loose Stools'], warnings: ['⚠️ Essential adjunct in acute diarrhea. Give for 14 days.'], orderSetTags: ['os_age'] },

    // --- RESPIRATORY ---
    { id: "rs_01", name: "Ascoril LS Junior Syrup", doseMg: 0, doseType: "fixed", maxMg: 0, div: 3, defaultFreq: "TID", conc: 0, vol: 5, category: "respiratory", indications: ['Cough', 'Wheezing'], warnings: ['⚠️ May cause tremors.'], orderSetTags: [] },
    { id: "rs_02", name: "Kuff-X Syrup", doseMg: 0, doseType: "fixed", maxMg: 0, div: 3, defaultFreq: "TID", conc: 0, vol: 5, category: "respiratory", indications: ['Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_03", name: "Kuff-D Syrup", doseMg: 0, doseType: "fixed", maxMg: 0, div: 2, defaultFreq: "BID", conc: 0, vol: 5, category: "respiratory", indications: ['Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_04", name: "Ambroxol 7.5mg/ml drops [Ambrolite]", doseMg: 1.5, doseType: "perDay", maxMg: 30, div: 3, defaultFreq: "TID", conc: 7.5, vol: 1, category: "respiratory", indications: ['Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_05", name: "Ambroxol 15mg/5ml syrup [Ambrolite]", doseMg: 1.5, doseType: "perDay", maxMg: 30, div: 3, defaultFreq: "TID", conc: 15, vol: 5, category: "respiratory", indications: ['Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_06", name: "Ambroxol 30mg/5ml syrup [Ambrolite]", doseMg: 1.5, doseType: "perDay", maxMg: 30, div: 3, defaultFreq: "TID", conc: 30, vol: 5, category: "respiratory", indications: ['Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_07", name: "Bromhexine HCl 4mg/5ml syrup [Bisolvon]", doseMg: 1, doseType: "perDay", maxMg: 8, div: 3, defaultFreq: "TID", conc: 4, vol: 5, category: "respiratory", indications: ['Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_08", name: "Butamirate citrate 5mg/ml drops [Sinecod]", doseMg: 1, doseType: "perDay", maxMg: 15, div: 3, defaultFreq: "TID", conc: 5, vol: 1, category: "respiratory", indications: ['Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_09", name: "Butamirate citrate 7.5mg/5ml syrup [Sinecod]", doseMg: 1, doseType: "perDay", maxMg: 15, div: 3, defaultFreq: "TID", conc: 7.5, vol: 5, category: "respiratory", indications: ['Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_10", name: "Carbocisteine 2% (100mg/5ml) [Mucoclear]", doseMg: 20, doseType: "perDay", maxMg: 750, div: 3, defaultFreq: "TID", conc: 100, vol: 5, category: "respiratory", indications: ['Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_11", name: "Carbocisteine 5% (250mg/5ml) [Mucoclear]", doseMg: 20, doseType: "perDay", maxMg: 750, div: 3, defaultFreq: "TID", conc: 250, vol: 5, category: "respiratory", indications: ['Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_12", name: "Dextromethorphan 15mg/5ml syrup [Alex]", doseMg: 1, doseType: "perDay", maxMg: 30, div: 3, defaultFreq: "TID", conc: 15, vol: 5, category: "respiratory", indications: ['Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_13", name: "Guaifenesin 100mg/5ml syrup [Robitussin]", doseMg: 10, doseType: "perDay", maxMg: 400, div: 4, defaultFreq: "QID", conc: 100, vol: 5, category: "respiratory", indications: ['Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_14", name: "Terbutaline 1.5mg/5ml syrup [Bricanyl]", doseMg: 0.05, doseType: "perDose", maxMg: 2.5, div: 1, defaultFreq: "TID", conc: 1.5, vol: 5, category: "respiratory", indications: ['Wheezing', 'Cough'], warnings: ['⚠️ May cause tachycardia and tremors.'], orderSetTags: ['os_asthma'] },
    { id: "rs_15", name: "Salbutamol 2mg/5ml syrup [Asthalin]", doseMg: 0.15, doseType: "perDose", maxMg: 4, div: 1, defaultFreq: "TID", conc: 2, vol: 5, category: "respiratory", indications: ['Wheezing', 'Cough', 'Shortness of Breath'], warnings: ['⚠️ May cause tachycardia and tremors.'], orderSetTags: ['os_asthma'] },
    { id: "rs_16", name: "Montelukast 4mg [Singulair]", doseMg: 0.2, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "QD (Evening)", conc: 4, vol: 1, category: "respiratory", indications: ['Wheezing', 'Cough'], warnings: [], orderSetTags: ['os_asthma'] },
    { id: "rs_17", name: "Chlorphen+Dextro (2/15) [Ascoril D]", doseMg: 1, doseType: "perDay", maxMg: 4, div: 3, defaultFreq: "TID", conc: 15, vol: 5, category: "respiratory", indications: ['Cough', 'Cold'], warnings: [], orderSetTags: [] },
    { id: "rs_18", name: "Chlorphen+Pseudo (2/30) [Sinarest]", doseMg: 4, doseType: "perDay", maxMg: 60, div: 3, defaultFreq: "TID", conc: 30, vol: 5, category: "respiratory", indications: ['Cold', 'Cough'], warnings: [], orderSetTags: ['os_uri'] },
    { id: "rs_19", name: "PCM+Chlorphen+Pseudo [Sinarest AF]", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, defaultFreq: "TID", conc: 125, vol: 5, category: "respiratory", indications: ['Fever', 'Cold', 'Cough'], warnings: ['⚠️ Avoid additional Paracetamol.'], orderSetTags: ['os_uri'] },
    { id: "rs_20", name: "Triprolidine+Pseudo (1.25/30) [Actifed]", doseMg: 4, doseType: "perDay", maxMg: 60, div: 3, defaultFreq: "TID", conc: 30, vol: 5, category: "respiratory", indications: ['Cold', 'Cough'], warnings: [], orderSetTags: [] },
    { id: "rs_21", name: "Guai+Tripro+Pseudo [Actifed Plus]", doseMg: 10, doseType: "perDay", maxMg: 400, div: 3, defaultFreq: "TID", conc: 100, vol: 5, category: "respiratory", indications: ['Cold', 'Cough'], warnings: [], orderSetTags: [] },

    // --- MUSCLE RELAXANTS (IAP Extracted) ---
    { id: "mr_01", name: "Inj. Neostigmine (0.5mg/ml)", doseMg: 0.04, doseType: "perDose", maxMg: 2.5, div: 1, defaultFreq: "STAT", conc: 0.5, vol: 1, category: "musclerelaxants", indications: ['Neuromuscular Blockade Reversal'], warnings: ['⚠️ Administer with Atropine to prevent bradycardia.'], orderSetTags: [] },
    { id: "mr_02", name: "Inj. Suxamethonium (50mg/ml)", doseMg: 1.5, doseType: "perDose", maxMg: 150, div: 1, defaultFreq: "STAT", conc: 50, vol: 1, category: "musclerelaxants", indications: ['Rapid Sequence Intubation'], warnings: ['⚠️ Risk of malignant hyperthermia and hyperkalemia.'], orderSetTags: [] },

    // --- VITAMINS & MINERALS (IAP Extracted) ---
    { id: "vm_01", name: "Syp. Vitamin A (100,000 IU/ml)", doseMg: 100000, doseType: "fixed", maxMg: 200000, div: 1, defaultFreq: "STAT (Prophylaxis)", conc: 100000, vol: 1, category: "vitamins", indications: ['Vitamin A Deficiency', 'Measles'], warnings: ['⚠️ Ensure appropriate age-based dosing (1L or 2L IU).'], orderSetTags: [] },
    { id: "vm_02", name: "Inj. Vitamin K / Phytomenadione (1mg/ml)", doseMg: 1, doseType: "fixed", maxMg: 10, div: 1, defaultFreq: "STAT", conc: 1, vol: 1, category: "vitamins", indications: ['Hemorrhagic Disease of Newborn', 'Coagulopathy'], warnings: [], orderSetTags: [] },
    { id: "vm_03", name: "Syp. Iron + Folic Acid (20mg/ml)", doseMg: 3, doseType: "perDay", maxMg: 60, div: 1, defaultFreq: "OD", conc: 20, vol: 1, category: "vitamins", indications: ['Anemia', 'Lethargy'], warnings: ['⚠️ Administer between meals for better absorption.'], orderSetTags: [] },
    { id: "vm_04", name: "Tab. Cholecalciferol (400 IU)", doseMg: 400, doseType: "fixed", maxMg: 400, div: 1, defaultFreq: "OD", conc: 400, vol: 1, category: "vitamins", indications: ['Vitamin D Deficiency', 'Rickets'], warnings: [], orderSetTags: [] },

    // --- ADDITIONAL GIT (IAP Extracted) ---
    { id: "gi_11", name: "Cap. Omeprazole (10mg)", doseMg: 1, doseType: "perDay", maxMg: 40, div: 1, defaultFreq: "OD", conc: 10, vol: 1, category: "git", indications: ['Abdominal Pain', 'Vomiting'], warnings: ['⚠️ Administer before meals.'], orderSetTags: [] },
    // --- EMERGENCY, ANAPHYLAXIS & ANTIDOTES (IAP Extracted) ---
    { id: "em_01", name: "Inj. Epinephrine / Adrenaline (1:1000, 1mg/ml)", doseMg: 0.01, doseType: "perDose", maxMg: 0.5, div: 1, defaultFreq: "STAT (IM)", conc: 1, vol: 1, category: "emergency", indications: ['Anaphylaxis', 'Cardiac Arrest', 'Severe Asthma'], warnings: ['⚠️ Give IM in anterolateral thigh for anaphylaxis.', 'Monitor HR closely.'], orderSetTags: [] },
    { id: "em_02", name: "Inj. Hydrocortisone (100mg vial)", doseMg: 5, doseType: "perDose", maxMg: 200, div: 1, defaultFreq: "STAT (IV)", conc: 100, vol: 2, category: "emergency", indications: ['Anaphylaxis', 'Severe Asthma', 'Adrenal Crisis'], warnings: ['⚠️ Reconstitute with sterile water.'], orderSetTags: ['os_asthma'] },
    { id: "em_03", name: "Inj. Atropine (0.6mg/ml)", doseMg: 0.02, doseType: "perDose", maxMg: 0.6, div: 1, defaultFreq: "STAT (IV/IM)", conc: 0.6, vol: 1, category: "emergency", indications: ['OP Poisoning', 'Bradycardia'], warnings: ['⚠️ Minimum dose is 0.1mg to prevent paradoxical bradycardia.'], orderSetTags: [] },
    { id: "em_04", name: "Inj. Naloxone (400mcg/ml)", doseMg: 0.1, doseType: "perDose", maxMg: 2, div: 1, defaultFreq: "STAT (IV/IM)", conc: 0.4, vol: 1, category: "emergency", indications: ['Opioid Overdose', 'Respiratory Depression'], warnings: ['⚠️ May need repeat doses due to short half-life.'], orderSetTags: [] },

    // --- NEUROLOGY / ANTICONVULSANTS (IAP Extracted) ---
    { id: "nu_01", name: "Inj. Midazolam (1mg/ml)", doseMg: 0.1, doseType: "perDose", maxMg: 5, div: 1, defaultFreq: "STAT (IV)", conc: 1, vol: 1, category: "neurology", indications: ['Active Seizure', 'Status Epilepticus', 'Sedation'], warnings: ['⚠️ Monitor for respiratory depression.', 'Nasal/Buccal dose is higher (0.2 mg/kg).'], orderSetTags: [] },
    { id: "nu_02", name: "Inj. Diazepam (5mg/ml)", doseMg: 0.3, doseType: "perDose", maxMg: 10, div: 1, defaultFreq: "STAT (Slow IV)", conc: 5, vol: 1, category: "neurology", indications: ['Active Seizure', 'Status Epilepticus'], warnings: ['⚠️ Give very slowly (1-2 mins) to avoid apnea.'], orderSetTags: [] },
    { id: "nu_03", name: "Inj. Phenytoin (50mg/ml)", doseMg: 20, doseType: "perDose", maxMg: 1000, div: 1, defaultFreq: "STAT (IV Loading)", conc: 50, vol: 1, category: "neurology", indications: ['Status Epilepticus'], warnings: ['⚠️ Dilute only in Normal Saline.', 'Do not exceed 1mg/kg/min infusion rate.'], orderSetTags: [] },
    { id: "nu_04", name: "Syp. Sodium Valproate (200mg/5ml)", doseMg: 20, doseType: "perDay", maxMg: 1000, div: 2, defaultFreq: "BID", conc: 200, vol: 5, category: "neurology", indications: ['Epilepsy Maintenance'], warnings: ['⚠️ Monitor liver function.', 'Risk of weight gain.'], orderSetTags: [] },
    { id: "nu_05", name: "Tab. Propranolol (20mg)", doseMg: 1, doseType: "perDay", maxMg: 40, div: 2, defaultFreq: "BID", conc: 20, vol: 1, category: "neurology", indications: ['Migraine Prophylaxis', 'Tremors'], warnings: ['⚠️ Contraindicated in Asthma.'], orderSetTags: [] },

    // --- TOPICAL: DERMA, OPHTHALMIC, ENT (IAP Extracted) ---
    { id: "tp_01", name: "Permethrin 5% Cream", doseMg: 1, doseType: "fixed", maxMg: 1, div: 1, defaultFreq: "STAT (Apply overnight)", conc: 1, vol: 1, category: "topical", indications: ['Scabies', 'Itching'], warnings: ['⚠️ Wash off after 8-14 hours.', 'Apply from neck down.'], orderSetTags: [] },
    { id: "tp_02", name: "Xylometazoline 0.05% Nasal Drops", doseMg: 1, doseType: "fixed", maxMg: 1, div: 1, defaultFreq: "BID x 3 days", conc: 1, vol: 1, category: "topical", indications: ['Cold', 'Nasal Congestion'], warnings: ['⚠️ Do not use for more than 5 days (Rebound congestion).'], orderSetTags: ['os_uri'] },
    { id: "tp_03", name: "Ciprofloxacin 0.3% Drops (Eye/Ear)", doseMg: 2, doseType: "fixed", maxMg: 2, div: 1, defaultFreq: "2 drops TID", conc: 2, vol: 1, category: "topical", indications: ['Ear Pain', 'Eye Discharge', 'Conjunctivitis'], warnings: [], orderSetTags: ['os_aom'] },
    { id: "tp_04", name: "Miconazole 2% Cream", doseMg: 1, doseType: "fixed", maxMg: 1, div: 1, defaultFreq: "Apply BID", conc: 1, vol: 1, category: "topical", indications: ['Skin Rash', 'Fungal Infection'], warnings: ['⚠️ Keep area dry.'], orderSetTags: [] }
];

    // --- CLINICAL NUTRITION DATABASE ---
    const foodsDb = [
        {name:"Boiled rice", cat:"Cereals", p:8.5, c:77, f:0, k:349},
        {name:"Raw rice", cat:"Cereals", p:7.5, c:76, f:0, k:346},
        {name:"Wheat", cat:"Cereals", p:12, c:71, f:0, k:346},
        {name:"Ragi", cat:"Cereals", p:7, c:72, f:0, k:328},
        {name:"Jowar", cat:"Cereals", p:10, c:72, f:0, k:349},
        {name:"Banana", cat:"Fruits", p:1.2, c:27, f:0, k:116},
        {name:"Apple", cat:"Fruits", p:0.2, c:13, f:0, k:59},
        {name:"Mango", cat:"Fruits", p:0.6, c:17, f:0, k:74},
        {name:"Dates(Dried)", cat:"Fruits", p:2.5, c:76, f:0, k:317},
        {name:"Sweet Lime", cat:"Fruits", p:1.5, c:11, f:0, k:60},
        {name:"Bengal gram", cat:"Pulses", p:17, c:61, f:0, k:360},
        {name:"Green gram", cat:"Pulses", p:24, c:60, f:0, k:348},
        {name:"Soya bean", cat:"Pulses", p:43, c:21, f:0, k:432},
        {name:"Rajmah", cat:"Pulses", p:23, c:60, f:0, k:346},
        {name:"Almond", cat:"Nuts", p:21, c:10, f:60, k:658},
        {name:"Groundnut", cat:"Nuts", p:25, c:26, f:40, k:567},
        {name:"Walnut", cat:"Nuts", p:34, c:11, f:64, k:687},
        {name:"Cow's milk", cat:"Dairy", p:3.3, c:4.4, f:4.1, k:67},
        {name:"Buffalo milk", cat:"Dairy", p:4.3, c:5.0, f:6.5, k:117},
        {name:"Breast milk", cat:"Dairy", p:1.1, c:7.4, f:3.4, k:65},
        {name:"Curds", cat:"Dairy", p:3.1, c:3.0, f:4.0, k:60},
        {name:"Chicken", cat:"Meat", p:25, c:0, f:0.6, k:109},
        {name:"Egg hen", cat:"Meat", p:13, c:0, f:13, k:173},
        {name:"Mutton", cat:"Meat", p:20, c:0, f:13, k:194},
        {name:"Potato", cat:"Vegetables", p:1, c:22, f:0.1, k:97},
        {name:"Carrot", cat:"Vegetables", p:1, c:11, f:0.2, k:48},
        {name:"Sweet potato", cat:"Vegetables", p:1, c:28, f:0.3, k:120},
        {name:"Beet root", cat:"Vegetables", p:1.7, c:9, f:0.1, k:43},
        {name:"Onion", cat:"Vegetables", p:1, c:11, f:0.1, k:50},
        {name:"Tapioca (chips)", cat:"Roots", p:1, c:82, f:0.3, k:338},
        {name:"Beef meat", cat:"Meat", p:19, c:0.2, f:10, k:410},
        {name:"Pork", cat:"Meat", p:18, c:0, f:4, k:114},
        {name:"Crab", cat:"Sea Food", p:9, c:3.3, f:1, k:59},
        {name:"Mackerel", cat:"Sea Food", p:19, c:0.5, f:1.7, k:93},
        {name:"Shrimp", cat:"Sea Food", p:68, c:0, f:8.5, k:349},
        {name:"Cauliflower", cat:"Vegetables", p:2.6, c:4, f:0.4, k:30},
        {name:"Capsicum", cat:"Vegetables", p:1.3, c:4.3, f:0.3, k:24},
        {name:"Coriander", cat:"Condiments", p:14, c:22, f:16, k:288},
        {name:"Garlic", cat:"Condiments", p:6, c:30, f:0.1, k:145},
        {name:"Ginger", cat:"Condiments", p:2, c:12, f:1, k:67},
        // --- Standardized Pediatric Clinical Nutrition Items ---
        { name: "Breastmilk / Formula (100ml)", cat: "Pediatric Diet", p: 1.5, c: 7.0, f: 3.5, k: 67 },
        { name: "Cow's Milk / Buffalo Milk (100ml)", cat: "Pediatric Diet", p: 3.5, c: 5.0, f: 6.5, k: 100 },
        { name: "Khichdi - Rice & Moong Dal (100g)", cat: "Pediatric Diet", p: 4.0, c: 20.0, f: 2.0, k: 120 },
        { name: "Plain Rice (100g cooked)", cat: "Pediatric Diet", p: 2.7, c: 28.0, f: 0.3, k: 130 },
        { name: "Thick Dal / Lentils (100g cooked)", cat: "Pediatric Diet", p: 9.0, c: 20.0, f: 0.5, k: 116 },
        { name: "Roti / Chapati (100g ~ 3 rotis)", cat: "Pediatric Diet", p: 9.0, c: 60.0, f: 2.0, k: 297 },
        { name: "Mashed Banana (100g)", cat: "Pediatric Diet", p: 1.1, c: 23.0, f: 0.3, k: 89 },
        { name: "Apple Puree (100g)", cat: "Pediatric Diet", p: 0.3, c: 14.0, f: 0.2, k: 52 },
        { name: "Boiled Egg (100g ~ 2 eggs)", cat: "Pediatric Diet", p: 13.0, c: 1.1, f: 11.0, k: 155 },
        { name: "Commercial Fortified Cereal (100g powder)", cat: "Pediatric Diet", p: 15.0, c: 65.0, f: 10.0, k: 412 },
        { name: "Curd / Yogurt (100g)", cat: "Pediatric Diet", p: 11.0, c: 4.0, f: 4.0, k: 98 },
        { name: "Idli (100g ~ 2 medium)", cat: "Pediatric Diet", p: 4.0, c: 30.0, f: 1.0, k: 144 },
        { name: "Dosa (100g ~ 1 large)", cat: "Pediatric Diet", p: 5.0, c: 55.0, f: 5.0, k: 280 },
        { name: "Upma / Suji (100g cooked)", cat: "Pediatric Diet", p: 3.5, c: 25.0, f: 1.5, k: 130 },
        
        // --- Specialized Clinical Formulas & Enteral Feeds ---
        { name: "Standard Infant Formula (20 kcal/oz)", cat: "Clinical Formula", p: 1.4, c: 7.3, f: 3.6, k: 67 },
        { name: "Preemie Formula (24 kcal/oz)", cat: "Clinical Formula", p: 2.2, c: 8.5, f: 4.2, k: 80 },
        { name: "High-Cal Preemie (30 kcal/oz)", cat: "Clinical Formula", p: 2.8, c: 10.6, f: 5.3, k: 100 },
        { name: "Extensively Hydrolyzed (e.g. Nutramigen)", cat: "Clinical Formula", p: 1.9, c: 7.5, f: 3.4, k: 68 },
        { name: "Amino Acid Formula (e.g. Neocate)", cat: "Clinical Formula", p: 1.8, c: 7.2, f: 3.4, k: 67 },
        { name: "Peptamen Junior (1.0 kcal/mL)", cat: "Enteral Feed", p: 3.0, c: 13.8, f: 3.8, k: 100 },
        { name: "Peptamen Junior 1.5 (1.5 kcal/mL)", cat: "Enteral Feed", p: 4.5, c: 17.0, f: 5.6, k: 150 },
        { name: "F-75 Therapeutic Diet (SAM)", cat: "Therapeutic", p: 0.9, c: 16.0, f: 3.2, k: 75 },
        { name: "F-100 Therapeutic Diet (SAM)", cat: "Therapeutic", p: 2.9, c: 11.0, f: 5.3, k: 100 }
    ];

    // Explicitly map these to the global window so the rest of the app can always find them
    window.foodsDb = foodsDb;

    // --- VACCINE SCHEMA ---
    const baseVaccineSchema = [
        { id: "bcg", name: "BCG", window: "At Birth", group: "Infant", baseOffsetWeeks: 0, strategy: "Give ASAP." },
        { id: "opv0", name: "OPV-0", window: "At Birth", group: "Infant", baseOffsetWeeks: 0, strategy: "Max 15 days." },
        { id: "hepB0", name: "Hepatitis B-0", window: "At Birth", group: "Infant", baseOffsetWeeks: 0, strategy: "Give within 24h." },
        { id: "penta1", name: "Pentavalent-1", window: "6 Wks", group: "Infant", baseOffsetWeeks: 6, strategy: "Max 1 yr." },
        { id: "opv1", name: "OPV-1", window: "6 Wks", group: "Infant", baseOffsetWeeks: 6, strategy: "Up to 5 yrs." },
        { id: "fipv1", name: "fIPV-1", window: "6 Wks", group: "Infant", baseOffsetWeeks: 6, strategy: "Fractional dose (ID)." },
        { id: "pcv1", name: "PCV-1", window: "6 Wks", group: "Infant", baseOffsetWeeks: 6, strategy: "Max 1 yr." },
        { id: "penta2", name: "Pentavalent-2", window: "10 Wks", group: "Infant", baseOffsetWeeks: 10, dependsOn: "penta1", minIntervalWeeks: 4, strategy: "4wk gap." },
        { id: "opv2", name: "OPV-2", window: "10 Wks", group: "Infant", baseOffsetWeeks: 10, dependsOn: "opv1", minIntervalWeeks: 4, strategy: "4wk gap." },
        { id: "penta3", name: "Pentavalent-3", window: "14 Wks", group: "Infant", baseOffsetWeeks: 14, dependsOn: "penta2", minIntervalWeeks: 4, strategy: "4wk gap." },
        { id: "opv3", name: "OPV-3", window: "14 Wks", group: "Infant", baseOffsetWeeks: 14, dependsOn: "opv2", minIntervalWeeks: 4, strategy: "4wk gap." },
        { id: "fipv2", name: "fIPV-2", window: "14 Wks", group: "Infant", baseOffsetWeeks: 14, dependsOn: "fipv1", minIntervalWeeks: 8, strategy: "8wk gap." },
        { id: "pcv2", name: "PCV-2", window: "14 Wks", group: "Infant", baseOffsetWeeks: 14, dependsOn: "pcv1", minIntervalWeeks: 8, strategy: "8wk gap." },
        { id: "mr1", name: "MR-1", window: "9 Mos", group: "Infant", baseOffsetWeeks: 39, strategy: "Up to 5 yrs." },
        { id: "pcvB", name: "PCV Booster", window: "9 Mos", group: "Infant", baseOffsetWeeks: 39, dependsOn: "pcv2", minIntervalWeeks: 24, strategy: "6mo gap." },
        { id: "je1", name: "JE-1", window: "9 Mos", group: "Infant", baseOffsetWeeks: 39, condition: "je", strategy: "Endemic areas." },
        { id: "mr2", name: "MR-2", window: "16-24 Mos", group: "Toddler", baseOffsetWeeks: 69, dependsOn: "mr1", minIntervalWeeks: 24, strategy: "6mo gap." },
        { id: "dptB1", name: "DPT Booster-1", window: "16-24 Mos", group: "Toddler", baseOffsetWeeks: 69, dependsOn: "penta3", minIntervalWeeks: 24, strategy: "6mo gap required." },
        { id: "je2", name: "JE-2", window: "16-24 Mos", group: "Toddler", baseOffsetWeeks: 69, condition: "je", dependsOn: "je1", minIntervalWeeks: 24, strategy: "6mo gap." },
        { id: "dptB2", name: "DPT Booster-2", window: "5-6 Yrs", group: "Toddler", baseOffsetWeeks: 260, strategy: "Max 7 yrs." },
        { id: "hpv1", name: "HPV-1", window: "9-14 Yrs", group: "Adolescent", baseOffsetWeeks: 468, condition: "female", strategy: "Girls only." },
        { id: "hpv2", name: "HPV-2", window: "6 Mos Post Dose 1", group: "Adolescent", baseOffsetWeeks: 494, condition: "female", dependsOn: "hpv1", minIntervalWeeks: 24, strategy: "6mo gap." },
        { id: "td10", name: "Td-10", window: "10 Yrs", group: "Adolescent", baseOffsetWeeks: 520, strategy: "Tetanus/Diphtheria." },
        { id: "td16", name: "Td-16", window: "16 Yrs", group: "Adolescent", baseOffsetWeeks: 832, strategy: "Tetanus/Diphtheria." }
    ];
    window.baseVaccineSchema = baseVaccineSchema;

    // --- MILESTONES SCHEMA ---
    const milestonesDb = {
        2: [ { id: "m2_1", domain: "Social", text: "Social smile.", sig: "Visual deficit." }, { id: "m2_2", domain: "Lang", text: "Coos.", sig: "Hearing deficit." }, { id: "m2_3", domain: "Motor", text: "Head steady.", sig: "Hypotonia." } ],
        4: [ { id: "m4_1", domain: "Social", text: "Laughs out loud.", sig: "Social delay." }, { id: "m4_2", domain: "Motor", text: "Reaches for toys.", sig: "Motor delay." }, { id: "m4_3", domain: "Motor", text: "Rolls tummy to back.", sig: "Hyper/hypotonia." } ],
        6: [ { id: "m6_1", domain: "Motor", text: "Sits without support.", sig: "CP red flag." }, { id: "m6_2", domain: "Lang", text: "Babbles.", sig: "Hearing loss." }, { id: "m6_3", domain: "Motor", text: "Transfers objects.", sig: "Hemiplegia." } ],
        9: [ { id: "m9_1", domain: "Motor", text: "Pincer grasp.", sig: "Fine motor delay." }, { id: "m9_2", domain: "Motor", text: "Pulls to stand.", sig: "Hypotonia." }, { id: "m9_3", domain: "Lang", text: "Responds to name.", sig: "Hearing/ASD." }, { id: "m9_4", domain: "Motor", text: "Pats a cake.", sig: "Coordination." } ],
        12: [ { id: "m12_1", domain: "Lang", text: "1-2 words.", sig: "Speech delay." }, { id: "m12_2", domain: "Motor", text: "Cruises/Walks.", sig: "Pathology." }, { id: "m12_3", domain: "Social", text: "Points to objects.", sig: "ASD risk." } ],
        18: [ { id: "m18_1", domain: "Motor", text: "Walks alone/backwards.", sig: "Neuro eval." }, { id: "m18_2", domain: "Lang", text: "10-15 words.", sig: "Speech delay." }, { id: "m18_3", domain: "Motor", text: "Uses spoon.", sig: "Coordination." } ],
        24: [ { id: "m24_1", domain: "Lang", text: "2-word sentences.", sig: "Speech eval." }, { id: "m24_2", domain: "Cognitive", text: "Points to 3 body parts.", sig: "Cognitive delay." }, { id: "m24_3", domain: "Social", text: "Parallel play.", sig: "ASD risk." } ],
        36: [ { id: "m36_1", domain: "Lang", text: "3-4 word sentences.", sig: "Articulation." }, { id: "m36_2", domain: "Motor", text: "Pedals tricycle.", sig: "Coordination." }, { id: "m36_3", domain: "Motor", text: "Copies a circle.", sig: "Visual-motor." } ]
    };
    window.milestonesDb = milestonesDb;