// --- 1. CLINICAL DATABASES ---
    const drugDb = {
        "antibiotics": [
            { name: "Amoxicillin 125mg/5ml", brand: "Novamox / Synmox", doseMg: 40, doseType: "perDay", maxMg: 500, div: 3, freq: "TID", conc: 125, vol: 5 },
            { name: "Amoxicillin 250mg/5ml", brand: "Novamox / Synmox", doseMg: 40, doseType: "perDay", maxMg: 500, div: 3, freq: "TID", conc: 250, vol: 5 },
            { name: "Amox+Clav 62.5mg/ml drops", brand: "Augmentin / Clavam", doseMg: 40, doseType: "perDay", maxMg: 875, div: 3, freq: "TID", conc: 62.5, vol: 1 },
            { name: "Amox+Clav 156mg/5ml", brand: "Augmentin / Clavam", doseMg: 40, doseType: "perDay", maxMg: 875, div: 3, freq: "TID", conc: 156, vol: 5 },
            { name: "Amox+Clav (200/28)mg/5ml", brand: "Advent", doseMg: 40, doseType: "perDay", maxMg: 875, div: 2, freq: "BID", conc: 200, vol: 5 },
            { name: "Amox+Clav 312mg/5ml", brand: "Augmentin Duo", doseMg: 40, doseType: "perDay", maxMg: 875, div: 3, freq: "TID", conc: 312, vol: 5 },
            { name: "Amox+Clav (400/57)mg/5ml", brand: "Clavam Forte", doseMg: 40, doseType: "perDay", maxMg: 875, div: 2, freq: "BID", conc: 400, vol: 5 },
            { name: "Amox+Clav (600/42.9)mg/5ml", brand: "Megamentin", doseMg: 90, doseType: "perDay", maxMg: 875, div: 2, freq: "BID", conc: 600, vol: 5 },
            { name: "Cefixime 100mg/5ml", brand: "Taxim-O / Zifi", doseMg: 8, doseType: "perDay", maxMg: 200, div: 2, freq: "BID", conc: 100, vol: 5 },
            { name: "Cefaclor 125mg/5ml", brand: "Keflor", doseMg: 20, doseType: "perDay", maxMg: 500, div: 3, freq: "TID", conc: 125, vol: 5 },
            { name: "Cefaclor 250mg/5ml", brand: "Keflor", doseMg: 20, doseType: "perDay", maxMg: 500, div: 3, freq: "TID", conc: 250, vol: 5 },
            { name: "Cefaclor 375mg/5ml", brand: "Keflor", doseMg: 20, doseType: "perDay", maxMg: 500, div: 3, freq: "TID", conc: 375, vol: 5 },
            { name: "Cefuroxime 125mg/5ml", brand: "Ceftum / Zocef", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, freq: "BID", conc: 125, vol: 5 },
            { name: "Cefuroxime 250mg/5ml", brand: "Ceftum / Zocef", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, freq: "BID", conc: 250, vol: 5 },
            { name: "Cefdinir 125mg/5ml", brand: "Adcef", doseMg: 14, doseType: "perDay", maxMg: 300, div: 1, freq: "QD or BID", conc: 125, vol: 5 },
            { name: "Cefdinir 250mg/5ml", brand: "Adcef", doseMg: 14, doseType: "perDay", maxMg: 300, div: 1, freq: "QD or BID", conc: 250, vol: 5 },
            { name: "Cephalexin 125mg/5ml", brand: "Sporidex", doseMg: 40, doseType: "perDay", maxMg: 500, div: 3, freq: "TID", conc: 125, vol: 5 },
            { name: "Cephalexin 250mg/5ml", brand: "Sporidex", doseMg: 40, doseType: "perDay", maxMg: 500, div: 3, freq: "TID", conc: 250, vol: 5 },
            { name: "Cefadroxil 125mg/5ml", brand: "Odoxil", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, freq: "BID", conc: 125, vol: 5 },
            { name: "Cefadroxil 250mg/5ml", brand: "Odoxil", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, freq: "BID", conc: 250, vol: 5 },
            { name: "Cefadroxil 500mg/5ml", brand: "Odoxil", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, freq: "BID", conc: 500, vol: 5 },
            { name: "Cephradine 125mg/5ml", doseMg: 25, doseType: "perDay", maxMg: 500, div: 2, freq: "BID", conc: 125, vol: 5 },
            { name: "Cephradine 250mg/5ml", doseMg: 25, doseType: "perDay", maxMg: 500, div: 2, freq: "BID", conc: 250, vol: 5 },
            { name: "Cefpodoxime 40mg/5ml", brand: "Macpod / Cepodem", doseMg: 10, doseType: "perDay", maxMg: 200, div: 2, freq: "BID", conc: 40, vol: 5 },
            { name: "Cefpodoxime 50mg/5ml", brand: "Macpod / Cepodem", doseMg: 10, doseType: "perDay", maxMg: 200, div: 2, freq: "BID", conc: 50, vol: 5 },
            { name: "Cefpodoxime 100mg/5ml", brand: "Macpod / Cepodem", doseMg: 10, doseType: "perDay", maxMg: 200, div: 2, freq: "BID", conc: 100, vol: 5 },
            { name: "Cefprozil 125mg/5ml", brand: "Refzil O", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, freq: "BID", conc: 125, vol: 5 },
            { name: "Cefprozil 250mg/5ml", brand: "Refzil O", doseMg: 30, doseType: "perDay", maxMg: 500, div: 2, freq: "BID", conc: 250, vol: 5 },
            { name: "Azithromycin 100mg/5ml", brand: "Azee / Zithrox", doseMg: 10, doseType: "perDose", maxMg: 500, div: 1, freq: "QD (3-5 days)", conc: 100, vol: 5 },
            { name: "Azithromycin 200mg/5ml", brand: "Azee / Zithrox", doseMg: 10, doseType: "perDose", maxMg: 500, div: 1, freq: "QD (3-5 days)", conc: 200, vol: 5 },
            { name: "Erythromycin 200mg/5ml", brand: "Erythrocin", doseMg: 40, doseType: "perDay", maxMg: 500, div: 4, freq: "QID", conc: 200, vol: 5 },
            { name: "Erythromycin 400mg/5ml", brand: "Erythrocin", doseMg: 40, doseType: "perDay", maxMg: 500, div: 4, freq: "QID", conc: 400, vol: 5 },
            { name: "Clarithromycin 125mg/5ml", brand: "ClariBid", doseMg: 15, doseType: "perDay", maxMg: 500, div: 2, freq: "BID", conc: 125, vol: 5 },
            { name: "Clarithromycin 250mg/5ml", brand: "ClariBid", doseMg: 15, doseType: "perDay", maxMg: 500, div: 2, freq: "BID", conc: 250, vol: 5 },
            { name: "Mebendazole 100mg/5ml", brand: "Mebex", doseMg: 100, doseType: "fixed", div: 1, freq: "Stat (Repeat 2wks)", conc: 100, vol: 5 },
            { name: "Metronidazole 125mg/5ml", brand: "Flagyl / Metrogyl", doseMg: 30, doseType: "perDay", maxMg: 500, div: 3, freq: "TID", conc: 125, vol: 5 },
            { name: "Metronidazole 200mg/5ml", brand: "Flagyl / Metrogyl", doseMg: 30, doseType: "perDay", maxMg: 500, div: 3, freq: "TID", conc: 200, vol: 5 },
            { name: "Co-trimoxazole (40/200)mg/5ml", brand: "Septran", doseMg: 8, doseType: "perDay", maxMg: 160, div: 2, freq: "BID", conc: 40, vol: 5 }
        ],
        "antipyretics": [
            { name: "Paracetamol 100mg/ml drops", brand: "Calpol / Crocin", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, freq: "Q6H PRN", conc: 100, vol: 1 },
            { name: "Paracetamol 120mg/5ml syrup", brand: "Calpol / Crocin", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, freq: "Q6H PRN", conc: 120, vol: 5 },
            { name: "Paracetamol 125mg/5ml syrup", brand: "Calpol / Crocin", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, freq: "Q6H PRN", conc: 125, vol: 5 },
            { name: "Paracetamol 250mg/5ml syrup", brand: "Calpol 250 / P-250", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, freq: "Q6H PRN", conc: 250, vol: 5 },
            { name: "Paracetamol 500 mg Tablet", brand: "Crocin 500 / Dolo", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, freq: "QID (PRN)", conc: 500, vol: 1 },
            { name: "Paracetamol 650 mg Tablet", brand: "Dolo 650", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, freq: "QID (PRN)", conc: 650, vol: 1 },
            { name: "Paracetamol Suppository 80mg", brand: "Neomol", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, freq: "Q6H PRN", conc: 80, vol: 1 },
            { name: "Paracetamol Suppository 120mg", brand: "Neomol", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, freq: "Q6H PRN", conc: 120, vol: 1 },
            { name: "Paracetamol Suppository 250mg", brand: "Neomol", doseMg: 15, doseType: "fixed", maxMg: 1000, div: 1, freq: "Q6H PRN", conc: 250, vol: 1 },
            { name: "Ibuprofen 40mg/ml drops", brand: "Ibugesic", doseMg: 10, doseType: "perDose", maxMg: 400, div: 1, freq: "Q6-8H", conc: 40, vol: 1 },
            { name: "Ibuprofen 100mg/5ml susp", brand: "Ibugesic / Brufen", doseMg: 10, doseType: "perDose", maxMg: 400, div: 1, freq: "Q6-8H", conc: 100, vol: 5 },
            { name: "Diclofenac Suppository 12.5mg", brand: "Voveran", doseMg: 1, doseType: "fixed", maxMg: 50, div: 1, freq: "BID or TID", conc: 12.5, vol: 1 },
            { name: "Diclofenac Suppository 25mg", brand: "Voveran", doseMg: 1, doseType: "fixed", maxMg: 50, div: 1, freq: "BID or TID", conc: 25, vol: 1 }
        ],
        "antihistamines": [
            { name: "Dimetindene maleate 1mg/ml drops", brand: "Fenistil", doseMg: 0.1, doseType: "perDay", maxMg: 1, div: 3, freq: "TID", conc: 1, vol: 1 },
            { name: "Dimetindene maleate 0.1mg/ml syrup", brand: "Fenistil", doseMg: 0.1, doseType: "perDay", maxMg: 1, div: 3, freq: "TID", conc: 0.1, vol: 1 },
            { name: "Chlorpheniramine 2mg/5ml syrup", brand: "Piriton", doseMg: 0.35, doseType: "perDay", maxMg: 4, div: 4, freq: "Q6H", conc: 2, vol: 5 },
            { name: "Cetirizine 10mg/ml drops", brand: "Cetzine / Zyrtec", doseMg: 0.25, doseType: "perDose", maxMg: 10, div: 1, freq: "QD", conc: 10, vol: 1 },
            { name: "Cetirizine 1mg/ml syrup", brand: "Cetzine / Zyrtec", doseMg: 0.25, doseType: "perDose", maxMg: 10, div: 1, freq: "QD", conc: 1, vol: 1 },
            { name: "Cetirizine 5mg/5ml syrup", brand: "Cetzine / Zyrtec", doseMg: 0.25, doseType: "perDose", maxMg: 10, div: 1, freq: "QD", conc: 5, vol: 5 },
            { name: "Levocetirizine 2.5mg/5ml syrup", brand: "L-Cetzine / Xyzal", doseMg: 0.125, doseType: "perDose", maxMg: 5, div: 1, freq: "QD", conc: 2.5, vol: 5 },
            { name: "Loratadine 1mg/ml syrup", brand: "Claritin", doseMg: 0.2, doseType: "perDose", maxMg: 10, div: 1, freq: "QD", conc: 1, vol: 1 },
            { name: "Desloratadine 0.5mg/ml syrup", brand: "Aerius", doseMg: 0.1, doseType: "perDose", maxMg: 5, div: 1, freq: "QD", conc: 0.5, vol: 1 },
            { name: "Fexofenadine 30mg/5ml susp", brand: "Allegra", doseMg: 2, doseType: "perDay", maxMg: 60, div: 2, freq: "BID", conc: 30, vol: 5 },
            { name: "Promethazine 6.25mg/5ml syrup", brand: "Phenergan", doseMg: 1, doseType: "perDay", maxMg: 25, div: 3, freq: "TID", conc: 6.25, vol: 5 },
            { name: "Dexamethasone 0.5mg/5ml syrup", brand: "Dexona", doseMg: 0.3, doseType: "perDose", maxMg: 10, div: 1, freq: "Stat or QD", conc: 0.5, vol: 5 },
            { name: "Prednisolone 15mg/5ml syrup", brand: "Omnacortil", doseMg: 1.5, doseType: "perDay", maxMg: 60, div: 2, freq: "BID", conc: 15, vol: 5 }
        ],
        "git": [
            { name: "Domperidone 1mg/ml syrup", brand: "Domstal", doseMg: 0.25, doseType: "perDose", maxMg: 10, div: 1, freq: "TID (Before meals)", conc: 1, vol: 1 },
            { name: "Metoclopramide 5mg/5ml syrup", brand: "Perinorm", doseMg: 0.15, doseType: "perDose", maxMg: 10, div: 1, freq: "TID", conc: 5, vol: 5 },
            { name: "Ondansetron 4mg/5ml syrup", brand: "Emeset / Zofer", doseMg: 0.15, doseType: "perDose", maxMg: 8, div: 1, freq: "TID or Stat", conc: 4, vol: 5 },
            { name: "Simethicone 40mg/ml drops", brand: "Colicaid", doseMg: 1, doseType: "perDose", maxMg: 40, div: 1, freq: "QID (After meals)", conc: 40, vol: 1 },
            { name: "Hyoscine butylbromide 5mg/5ml", brand: "Buscopan", doseMg: 0.5, doseType: "perDose", maxMg: 20, div: 1, freq: "TID", conc: 5, vol: 5 },
            { name: "Prifinium bromide 7.5mg/5ml", doseMg: 1, doseType: "perDose", maxMg: 30, div: 1, freq: "TID", conc: 7.5, vol: 5 },
            { name: "Loperamide 1mg/5ml syrup", brand: "Imodium", doseMg: 0.1, doseType: "perDose", maxMg: 2, div: 1, freq: "BID (Avoid <2 yrs)", conc: 1, vol: 5 },
            { name: "Lactulose 66.7g/100ml syrup", brand: "Duphalac / Looz", doseMg: 667, doseType: "perDay", maxMg: 2000, div: 2, freq: "BID", conc: 667, vol: 1 },
            { name: "Glycerin Suppository", brand: "Hallens", doseMg: 1, doseType: "fixed", div: 1, freq: "PRN", conc: 1, vol: 1 }
        ],
        "respiratory": [
            { name: "Ascoril LS Junior Syrup", brand: "Ascoril LS", doseMg: 0, doseType: "fixed", div: 3, freq: "TID", conc: 0, vol: 5 },
            { name: "Kuff-X Syrup", doseMg: 0, doseType: "fixed", div: 3, freq: "TID", conc: 0, vol: 5 },
            { name: "Kuff-D Syrup", doseMg: 0, doseType: "fixed", div: 2, freq: "BID", conc: 0, vol: 5 },
            { name: "Ambroxol 7.5mg/ml drops", brand: "Ambrolite", doseMg: 1.5, doseType: "perDay", maxMg: 30, div: 3, freq: "TID", conc: 7.5, vol: 1 },
            { name: "Ambroxol 15mg/5ml syrup", brand: "Ambrolite", doseMg: 1.5, doseType: "perDay", maxMg: 30, div: 3, freq: "TID", conc: 15, vol: 5 },
            { name: "Ambroxol 30mg/5ml syrup", brand: "Ambrolite", doseMg: 1.5, doseType: "perDay", maxMg: 30, div: 3, freq: "TID", conc: 30, vol: 5 },
            { name: "Bromhexine HCl 4mg/5ml syrup", brand: "Bisolvon", doseMg: 1, doseType: "perDay", maxMg: 8, div: 3, freq: "TID", conc: 4, vol: 5 },
            { name: "Butamirate citrate 5mg/ml drops", brand: "Sinecod", doseMg: 1, doseType: "perDay", maxMg: 15, div: 3, freq: "TID", conc: 5, vol: 1 },
            { name: "Butamirate citrate 7.5mg/5ml syrup", brand: "Sinecod", doseMg: 1, doseType: "perDay", maxMg: 15, div: 3, freq: "TID", conc: 7.5, vol: 5 },
            { name: "Carbocisteine 2% (100mg/5ml)", brand: "Mucoclear", doseMg: 20, doseType: "perDay", maxMg: 750, div: 3, freq: "TID", conc: 100, vol: 5 },
            { name: "Carbocisteine 5% (250mg/5ml)", brand: "Mucoclear", doseMg: 20, doseType: "perDay", maxMg: 750, div: 3, freq: "TID", conc: 250, vol: 5 },
            { name: "Dextromethorphan 15mg/5ml syrup", brand: "Alex", doseMg: 1, doseType: "perDay", maxMg: 30, div: 3, freq: "TID", conc: 15, vol: 5 },
            { name: "Guaifenesin 100mg/5ml syrup", brand: "Robitussin", doseMg: 10, doseType: "perDay", maxMg: 400, div: 4, freq: "QID", conc: 100, vol: 5 },
            { name: "Terbutaline 1.5mg/5ml syrup", brand: "Bricanyl", doseMg: 0.05, doseType: "perDose", maxMg: 2.5, div: 1, freq: "TID", conc: 1.5, vol: 5 },
            { name: "Salbutamol 2mg/5ml syrup", brand: "Asthalin", doseMg: 0.15, doseType: "perDose", maxMg: 4, div: 1, freq: "TID", conc: 2, vol: 5 },
            { name: "Montelukast 4mg/5mg/10mg", brand: "Singulair / Montair", doseMg: 0.2, doseType: "perDose", maxMg: 10, div: 1, freq: "QD (Evening)", conc: 4, vol: 1 },
            { name: "Chlorpheniramine+Dextro (2/15)", brand: "Ascoril D", doseMg: 1, doseType: "perDay", maxMg: 4, div: 3, freq: "TID", conc: 15, vol: 5 },
            { name: "Chlorphen+Pseudo (2/30)", brand: "Sinarest", doseMg: 4, doseType: "perDay", maxMg: 60, div: 3, freq: "TID", conc: 30, vol: 5 },
            { name: "PCM+Chlorphen+Pseudo syrup", brand: "Sinarest AF", doseMg: 15, doseType: "perDose", maxMg: 1000, div: 1, freq: "TID", conc: 125, vol: 5 },
            { name: "Triprolidine+Pseudo (1.25/30)", brand: "Actifed", doseMg: 4, doseType: "perDay", maxMg: 60, div: 3, freq: "TID", conc: 30, vol: 5 },
            { name: "Guai+Tripro+Pseudo syrup", brand: "Actifed Plus", doseMg: 10, doseType: "perDay", maxMg: 400, div: 3, freq: "TID", conc: 100, vol: 5 }
        ]
    };

    const foodsDb = [
        {name:"Boiled rice", cat:"Cereals", p:8.5, c:77, f:0, k:349},
        {name:"Raw rice", cat:"Cereals", p:7.5, c:76, f:0, k:346},
        {name:"Wheat", cat:"Cereals", p:12, c:71, f:0, k:346},
        {name:"Ragi", cat:"Cereals", p:7, c:72, f:0, k:328},
        {name:"Jowar", cat:"Cereals", p:10, c:72, f:0, k:349},
        {name:"Banana", cat:"Fruits", p:1.2, c:27, f:0, k:116},
        {name:"Apple", cat:"Fruits", p:0.2, c:13, f:0, k:59},
        {name:"Mango", cat:"Fruits", p:0.6, c:17, f:0, k:74},
        {name:"Dates(Dried)", cat:"Fruits", p:2.5, c:76, f:0, k:317},
        {name:"Sweet Lime", cat:"Fruits", p:1.5, c:11, f:0, k:60},
        {name:"Bengal gram", cat:"Pulses", p:17, c:61, f:0, k:360},
        {name:"Green gram", cat:"Pulses", p:24, c:60, f:0, k:348},
        {name:"Soya bean", cat:"Pulses", p:43, c:21, f:0, k:432},
        {name:"Rajmah", cat:"Pulses", p:23, c:60, f:0, k:346},
        {name:"Almond", cat:"Nuts", p:21, c:10, f:60, k:658},
        {name:"Groundnut", cat:"Nuts", p:25, c:26, f:40, k:567},
        {name:"Walnut", cat:"Nuts", p:34, c:11, f:64, k:687},
        {name:"Cow's milk", cat:"Dairy", p:3.3, c:4.4, f:4.1, k:67},
        {name:"Buffalo milk", cat:"Dairy", p:4.3, c:5.0, f:6.5, k:117},
        {name:"Breast milk", cat:"Dairy", p:1.1, c:7.4, f:3.4, k:65},
        {name:"Curds", cat:"Dairy", p:3.1, c:3.0, f:4.0, k:60},
        {name:"Chicken", cat:"Meat", p:25, c:0, f:0.6, k:109},
        {name:"Egg hen", cat:"Meat", p:13, c:0, f:13, k:173},
        {name:"Mutton", cat:"Meat", p:20, c:0, f:13, k:194},
        {name:"Potato", cat:"Vegetables", p:1, c:22, f:0.1, k:97},
        {name:"Carrot", cat:"Vegetables", p:1, c:11, f:0.2, k:48},
        {name:"Sweet potato", cat:"Vegetables", p:1, c:28, f:0.3, k:120},
        {name:"Beet root", cat:"Vegetables", p:1.7, c:9, f:0.1, k:43},
        {name:"Onion", cat:"Vegetables", p:1, c:11, f:0.1, k:50},
        {name:"Tapioca (chips)", cat:"Roots", p:1, c:82, f:0.3, k:338},
        {name:"Beef meat", cat:"Meat", p:19, c:0.2, f:10, k:410},
        {name:"Pork", cat:"Meat", p:18, c:0, f:4, k:114},
        {name:"Crab", cat:"Sea Food", p:9, c:3.3, f:1, k:59},
        {name:"Mackerel", cat:"Sea Food", p:19, c:0.5, f:1.7, k:93},
        {name:"Shrimp", cat:"Sea Food", p:68, c:0, f:8.5, k:349},
        {name:"Cauliflower", cat:"Vegetables", p:2.6, c:4, f:0.4, k:30},
        {name:"Capsicum", cat:"Vegetables", p:1.3, c:4.3, f:0.3, k:24},
        {name:"Coriander", cat:"Condiments", p:14, c:22, f:16, k:288},
        {name:"Garlic", cat:"Condiments", p:6, c:30, f:0.1, k:145},
        {name:"Ginger", cat:"Condiments", p:2, c:12, f:1, k:67}
    ];

    const baseVaccineSchema = [
        { id: "bcg", name: "BCG", window: "At Birth", group: "Infant", baseOffsetWeeks: 0, strategy: "Give ASAP." },
        { id: "opv0", name: "OPV-0", window: "At Birth", group: "Infant", baseOffsetWeeks: 0, strategy: "Max 15 days." },
        { id: "hepB0", name: "Hepatitis B-0", window: "At Birth", group: "Infant", baseOffsetWeeks: 0, strategy: "Give within 24h." },
        { id: "penta1", name: "Pentavalent-1", window: "6 Wks", group: "Infant", baseOffsetWeeks: 6, strategy: "Max 1 yr." },
        { id: "opv1", name: "OPV-1", window: "6 Wks", group: "Infant", baseOffsetWeeks: 6, strategy: "Up to 5 yrs." },
        { id: "fipv1", name: "fIPV-1", window: "6 Wks", group: "Infant", baseOffsetWeeks: 6, strategy: "Fractional dose (ID)." },
        { id: "pcv1", name: "PCV-1", window: "6 Wks", group: "Infant", baseOffsetWeeks: 6, strategy: "Max 1 yr." },
        { id: "penta2", name: "Pentavalent-2", window: "10 Wks", group: "Infant", baseOffsetWeeks: 10, dependsOn: "penta1", minIntervalWeeks: 4, strategy: "4wk gap." },
        { id: "opv2", name: "OPV-2", window: "10 Wks", group: "Infant", baseOffsetWeeks: 10, dependsOn: "opv1", minIntervalWeeks: 4, strategy: "4wk gap." },
        { id: "penta3", name: "Pentavalent-3", window: "14 Wks", group: "Infant", baseOffsetWeeks: 14, dependsOn: "penta2", minIntervalWeeks: 4, strategy: "4wk gap." },
        { id: "opv3", name: "OPV-3", window: "14 Wks", group: "Infant", baseOffsetWeeks: 14, dependsOn: "opv2", minIntervalWeeks: 4, strategy: "4wk gap." },
        { id: "fipv2", name: "fIPV-2", window: "14 Wks", group: "Infant", baseOffsetWeeks: 14, dependsOn: "fipv1", minIntervalWeeks: 8, strategy: "8wk gap." },
        { id: "pcv2", name: "PCV-2", window: "14 Wks", group: "Infant", baseOffsetWeeks: 14, dependsOn: "pcv1", minIntervalWeeks: 8, strategy: "8wk gap." },
        { id: "mr1", name: "MR-1", window: "9 Mos", group: "Infant", baseOffsetWeeks: 39, strategy: "Up to 5 yrs." },
        { id: "pcvB", name: "PCV Booster", window: "9 Mos", group: "Infant", baseOffsetWeeks: 39, dependsOn: "pcv2", minIntervalWeeks: 24, strategy: "6mo gap." },
        { id: "je1", name: "JE-1", window: "9 Mos", group: "Infant", baseOffsetWeeks: 39, condition: "je", strategy: "Endemic areas." },
        { id: "mr2", name: "MR-2", window: "16-24 Mos", group: "Toddler", baseOffsetWeeks: 69, dependsOn: "mr1", minIntervalWeeks: 24, strategy: "6mo gap." },
        { id: "dptB1", name: "DPT Booster-1", window: "16-24 Mos", group: "Toddler", baseOffsetWeeks: 69, dependsOn: "penta3", minIntervalWeeks: 24, strategy: "6mo gap required." },
        { id: "je2", name: "JE-2", window: "16-24 Mos", group: "Toddler", baseOffsetWeeks: 69, condition: "je", dependsOn: "je1", minIntervalWeeks: 24, strategy: "6mo gap." },
        { id: "dptB2", name: "DPT Booster-2", window: "5-6 Yrs", group: "Toddler", baseOffsetWeeks: 260, strategy: "Max 7 yrs." },
        { id: "hpv1", name: "HPV-1", window: "9-14 Yrs", group: "Adolescent", baseOffsetWeeks: 468, condition: "female", strategy: "Girls only." },
        { id: "hpv2", name: "HPV-2", window: "6 Mos Post Dose 1", group: "Adolescent", baseOffsetWeeks: 494, condition: "female", dependsOn: "hpv1", minIntervalWeeks: 24, strategy: "6mo gap." },
        { id: "td10", name: "Td-10", window: "10 Yrs", group: "Adolescent", baseOffsetWeeks: 520, strategy: "Tetanus/Diphtheria." },
        { id: "td16", name: "Td-16", window: "16 Yrs", group: "Adolescent", baseOffsetWeeks: 832, strategy: "Tetanus/Diphtheria." }
    ];

    const milestonesDb = {
        2: [ { id: "m2_1", domain: "Social", text: "Social smile.", sig: "Visual deficit." }, { id: "m2_2", domain: "Lang", text: "Coos.", sig: "Hearing deficit." }, { id: "m2_3", domain: "Motor", text: "Head steady.", sig: "Hypotonia." } ],
        4: [ { id: "m4_1", domain: "Social", text: "Laughs out loud.", sig: "Social delay." }, { id: "m4_2", domain: "Motor", text: "Reaches for toys.", sig: "Motor delay." }, { id: "m4_3", domain: "Motor", text: "Rolls tummy to back.", sig: "Hyper/hypotonia." } ],
        6: [ { id: "m6_1", domain: "Motor", text: "Sits without support.", sig: "CP red flag." }, { id: "m6_2", domain: "Lang", text: "Babbles.", sig: "Hearing loss." }, { id: "m6_3", domain: "Motor", text: "Transfers objects.", sig: "Hemiplegia." } ],
        9: [ { id: "m9_1", domain: "Motor", text: "Pincer grasp.", sig: "Fine motor delay." }, { id: "m9_2", domain: "Motor", text: "Pulls to stand.", sig: "Hypotonia." }, { id: "m9_3", domain: "Lang", text: "Responds to name.", sig: "Hearing/ASD." }, { id: "m9_4", domain: "Motor", text: "Pats a cake.", sig: "Coordination." } ],
        12: [ { id: "m12_1", domain: "Lang", text: "1-2 words.", sig: "Speech delay." }, { id: "m12_2", domain: "Motor", text: "Cruises/Walks.", sig: "Pathology." }, { id: "m12_3", domain: "Social", text: "Points to objects.", sig: "ASD risk." } ],
        18: [ { id: "m18_1", domain: "Motor", text: "Walks alone/backwards.", sig: "Neuro eval." }, { id: "m18_2", domain: "Lang", text: "10-15 words.", sig: "Speech delay." }, { id: "m18_3", domain: "Motor", text: "Uses spoon.", sig: "Coordination." } ],
        24: [ { id: "m24_1", domain: "Lang", text: "2-word sentences.", sig: "Speech eval." }, { id: "m24_2", domain: "Cognitive", text: "Points to 3 body parts.", sig: "Cognitive delay." }, { id: "m24_3", domain: "Social", text: "Parallel play.", sig: "ASD risk." } ],
        36: [ { id: "m36_1", domain: "Lang", text: "3-4 word sentences.", sig: "Articulation." }, { id: "m36_2", domain: "Motor", text: "Pedals tricycle.", sig: "Coordination." }, { id: "m36_3", domain: "Motor", text: "Copies a circle.", sig: "Visual-motor." } ]
    };